### ISSUE TITLE
运行就出现 这个个错误 ？

### ISSUE THREAD

**Issue by jetBn** [uiwjs/react-codemirror#105]
![image](https://user-images.githubusercontent.com/26957220/115982845-98c8a900-a5d0-11eb-800a-078a9ef6282d.png)

**Comment by jaywcjlove** [comment]
@jetBn 你可以使用 https://codesandbox.io/ 创建一个实例我看看，不知道你的运行环境

**Comment by jetBn** [comment]
我使用了ant from.item 的原因

**Comment by jetBn** [comment]
解决了 不用它的name字段就可以了
