### ISSUE TITLE
Interested in adding testing?

### ISSUE THREAD

**Issue by ruslanguns** [uiwjs/react-codemirror#106]
I am looking at your package and it's very promising, I was wondering if you are interested, What exactly would you test in this project to ensure that it works properly?

If you are interested I could help you write these tests.

**Comment by jaywcjlove** [comment]
@ruslanguns Welcome to submit test cases

**Comment by jaywcjlove** [comment]
[![Coverage Status](https://uiwjs.github.io/react-codemirror/coverage/badges.svg)](https://uiwjs.github.io/react-codemirror/coverage/lcov-report/)
