### ISSUE TITLE
TypeError: name.toLowerCase is not a function in mode option

### ISSUE THREAD

**Issue by ThomasDuin** [uiwjs/react-codemirror#108]
The documentation says you can also use an object as a configuration for prop mode. When I use the example ( {name: "javascript", json: true}) it says name.toLowerCase is not a function. Is this a bug regarding this package?

> /** string|object. The mode to use. When not given, this will default to the first mode that was loaded.
> It may be a string, which either simply names the mode or is a MIME type associated with the mode.
> Alternatively, it may be an object containing configuration options for the mode,
> with a name property that names the mode (for example {name: "javascript", json: true}). */
> mode?: any;

> meta.js:213 Uncaught (in promise) TypeError: name.toLowerCase is not a function
>     at Function.CodeMirror.findModeByName (meta.js:213)
>     at _callee$ (index.js:79)
>     at tryCatch (runtime.js:63)
>     at Generator.invoke [as _invoke] (runtime.js:293)
>     at Generator.next (runtime.js:118)
>     at asyncGeneratorStep (asyncToGenerator.js:3)
>     at _next (asyncToGenerator.js:25)
>     at asyncToGenerator.js:32
>     at new Promise (<anonymous>)
>     at asyncToGenerator.js:21

**Comment by jaywcjlove** [comment]
@ThomasDuin Upgrade `+ @uiw/react-codemirror@3.0.7`

**Comment by ThomasDuin** [comment]
Thank you for responding so quickly and trying to get a fix out there, but I still seem to get the same error.

**Comment by ThomasDuin** [comment]
https://codesandbox.io/s/loving-cohen-ig1b3?file=/src/CodeMirrorComponent.js

**Comment by jaywcjlove** [comment]
@ThomasDuin 

```jsx
<CodeMirror
  value={code}
  options={{
    theme: "monokai",
    keyMap: "sublime",
-    mode: { name: "javascript", json: true }
+    mode: 'javascript'
  }}
/>
```

**Comment by ThomasDuin** [comment]
The json property doesn't do anything?

**Comment by raquelhortab** [comment]
I'm trying to use the `options` prop but it does nothing, the only change I see is that the outer div in the DOM has `options="[object Object]"` so basically it seems to be passing the prop directly to the DOM element but not using it at all.

**Comment by jaywcjlove** [comment]
@raquelhortab https://github.com/uiwjs/react-codemirror/issues/88#issuecomment-914185563

`options` parameter does not exist in [`v4+`](https://github.com/uiwjs/react-codemirror/issues/88#issuecomment-914185563) version

**Comment by raquelhortab** [comment]
oh! and how are we suposed to use codemirror's configuration options? ([this](https://codemirror.net/doc/manual.html#api_marker) and [this](https://codemirror.net/doc/manual.html#config))

**Comment by jaywcjlove** [comment]
@raquelhortab Downgrade to version 3.0.

**Comment by raquelhortab** [comment]
> @raquelhortab Downgrade to version 3.0.

oh... okay! Is there any way I can get the bundled version for v3? Just like you fix it up yesterday for v4? Or get the commands needed to generate it myself. I am sorry to be bothering, if that is an inconvenience I'll try to settle with v4 or find an alternative library. Thanks for the support!

**Comment by raquelhortab** [comment]
I think I got it, I'll leave it here in case someone need it 
https://unpkg.com/@uiw/react-codemirror@3.2.1/lib/index.js
