### ISSUE TITLE
处理事件有 bug

### ISSUE THREAD

**Issue by lxfriday** [uiwjs/react-codemirror#13]
type 定义
![image](https://user-images.githubusercontent.com/20264467/66448200-635a7a00-ea83-11e9-9425-9c034eb25d69.png)

处理事件的函数
![image](https://user-images.githubusercontent.com/20264467/66448179-5047aa00-ea83-11e9-96bb-a674033ebee9.png)

现象
![image](https://user-images.githubusercontent.com/20264467/66448217-710fff80-ea83-11e9-87e4-a5f95b22255c.png)

![image](https://user-images.githubusercontent.com/20264467/66448264-91d85500-ea83-11e9-8e2d-0bda182dbc35.png)

---
问题

比如 `onDragOver` 这种有两个大写字母的事件，只会转化成 `dragOver` ，绑定的是 `dragOver` 而不是 `dragover`，所以会失效。

临时解决办法

绑定事件用 `onDragover` `onDragenter` 这种

修复代码

```js
const eventHandle = propNames.filter((prop) => {
  return /^on+/.test(prop);
});
// eventHandle 中确定都是 on 开头的

eventHandle.forEach((ele) => {
  // 直接去掉 on，然后小写化
  eventDict[ele] = ele.slice(2).toLowerCase();
});

```

**Comment by jaywcjlove** [comment]
@lxfriday 欢迎提交一个 PR，谢谢！

**Comment by lxfriday** [comment]
@jaywcjlove 稍后提交 :p
