### ISSUE TITLE
addon lint doesn't work

### ISSUE THREAD

**Issue by LegendLeo** [uiwjs/react-codemirror#135]
![image](https://user-images.githubusercontent.com/25115173/130760622-94853be1-5945-4741-b6b1-9aaec6ab2753.png)
code like codemirror document for lint javascript code, but doesn't work
和官方文档一样编写的lint相关代码，并不起作用
![image](https://user-images.githubusercontent.com/25115173/130760960-298a8fb5-ca29-4c62-b72b-ed3da91b7942.png)

**Comment by jaywcjlove** [comment]
@LegendLeo 这个可能是官方包的问题，你可以去 codemirror 仓库提issue。

**Comment by jaywcjlove** [comment]
@LegendLeo 这个可能是官方包的问题，你可以去 codemirror 仓库提issue。
