### ISSUE TITLE
What's the difference between react-codemirror and react-codemirror2 ?

### ISSUE THREAD

**Issue by sidwebworks** [uiwjs/react-codemirror#143]
Hi, I am a little confused on what are the main differences/changes between react-code-mirror and this one https://github.com/scniro/react-codemirror2

**Comment by jaywcjlove** [comment]
1. When `react-codemirror` was developed, `react-codemirror2` has stopped updating.
2. Fix some issue in react-codemirror2.
3. There are better sample previews.
4. Fix some types of issue.
5. Support [cjs and esm](https://github.com/uiwjs/react-codemirror/blob/fbbf5dea3ff6fe0b4e0ee6addcb3a373ca607777/package.json#L6-L7), [open in unpkg](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-codemirror/file/README.md)

**Comment by jaywcjlove** [comment]
@sidwebworks Will try to upgrade Codemirror 6 in the future. #88

**Comment by sidwebworks** [comment]
Yeah got it, I saw some other things you made! I Gotta admit damn good job mate! I would also love to contribute. Recently I and another contributor have been working to bring back the TSDX library after the author decided to abandon the project and so far it is looking good. I would love to work on some of your projects and contribute.

**Comment by sidwebworks** [comment]
Although I noticed the lib doesn't support SSR right? Do you have any plans to add it?

**Comment by jaywcjlove** [comment]
@sidwebworks  Server-side rendering is not supported because of codemirror. But it may have some solutions. https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

Welcome to participate in the project and make contributions.

@sidwebworks thx!

**Comment by sidwebworks** [comment]
Thanks man! I think I will close this now. Keep up the good work.
