### ISSUE TITLE
It does not support editable prop?

### ISSUE THREAD

**Issue by sealiuhailin** [uiwjs/react-codemirror#169]
![image](https://user-images.githubusercontent.com/26757438/133542737-705b09fe-ce98-4dfa-b67f-6fa99b4b93a4.png)
i see this prop on the document, but it doesn't seem to actually work.

**Comment by jaywcjlove** [comment]
@sealiuhailin  Upgrade `@uiw/react-codemirror@4.0.0`

**Comment by sealiuhailin** [comment]
> @sealiuhailin Upgrade `@uiw/react-codemirror@4.0.0`

Thanks, the problem is solved.
