### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'theme')

### ISSUE THREAD

**Issue by JQzhong-Fruen** [uiwjs/react-codemirror#184]
![image](https://user-images.githubusercontent.com/74750580/135212153-8a88e6bf-98d1-415a-b39c-812c7bd42468.png)

**Comment by jaywcjlove** [comment]
@JQzhong-Fruen Example: https://codesandbox.io/embed/react-codemirror-example-codemirror-6-slvju?fontsize=14&hidenavigation=1&theme=dark
