### ISSUE TITLE
在modal弹框中使用react-codemirror的问题

### ISSUE THREAD

**Issue by NsNe** [uiwjs/react-codemirror#20]
- 操作
在modal弹框中使用react-codemirror，控制modal的显示与隐藏

- 现象
出现文字被截断，行号不出现，无光标(光标位于行号底层，看不见)
![image](https://user-images.githubusercontent.com/25630824/72590817-9d1c0600-3939-11ea-83f8-d1fbd5e0279d.png)

- 期望结果
正常显示，正常输入
![image](https://user-images.githubusercontent.com/25630824/72590839-aa38f500-3939-11ea-914a-68af6948bf18.png)

**Comment by jaywcjlove** [comment]
@NsNe 可否给出实例我调试一哈？

**Comment by NsNe** [comment]
> @NsNe 可否给出实例我调试一哈？

https://codesandbox.io/s/competent-wilbur-eevp1

**Comment by jaywcjlove** [comment]
@NsNe 删除下面配置选项即可，实例预览：https://codesandbox.io/s/react-codemirror-demo-20-o8ike

```diff
  const codeOptions = {
    theme: "monokai",
    mode: "text/x-sql",
    lineNumbers: true,
    autoRefresh: true,
    tabSize: 2,
    // 当前行背景高亮
    styleActiveLine: true,
    // 代码折叠
    lineWrapping: true,
    foldGutter: true,
-    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
  };
```

**Comment by NsNe** [comment]
> @NsNe 删除下面配置选项即可，实例预览：https://codesandbox.io/s/react-codemirror-demo-20-o8ike
> 
> ```diff
>   const codeOptions = {
>     theme: "monokai",
>     mode: "text/x-sql",
>     lineNumbers: true,
>     autoRefresh: true,
>     tabSize: 2,
>     // 当前行背景高亮
>     styleActiveLine: true,
>     // 代码折叠
>     lineWrapping: true,
>     foldGutter: true,
> -    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
>   };
> ```
是的，最开始是这个问题，我去掉了fold相关的。然后还会偶现下面这样的问题。
![image](https://user-images.githubusercontent.com/25630824/72676499-cae58400-3acc-11ea-8571-9fbf3cb3680f.png)

那我先close了，后续如果遇到，再来反馈！

**Comment by jaywcjlove** [comment]
@NsNe 如果你定义了 `gutters ` 参数，你是要写对应的样式的。

**Comment by NsNe** [comment]
> @NsNe 如果你定义了 `gutters ` 参数，你是要写对应的样式的。
没有定义gutters参数，这个待我能完全复现再来反馈，感谢您的解答 💯
