### ISSUE TITLE
onChange uses old prop

### ISSUE THREAD

**Issue by Pitel** [uiwjs/react-codemirror#205]
I have my UI, and there are tabs with languages (english, german, etc.) so that when you change the tab, you are editing different language.

Now, I have my `TextEditor` functional component with codemirror (using `useCodeMirror` hook) and it has props:
* `languageId` (0: en, 1: de)
* `text` The string

So, in summary, somehting like this (sorry, I'm not writing JS/TS/JSX, because my project is using Kotlin/JS, but I don't think that's an issue, more in that later, but it's just a pseudocode):
```
texts = ["Hello", "Gutten tag"] // Fetched, just and example

tab = useState(0)

<Tabs tab={{tab}}>
  <!-- create tabs for languages -->
</Tabs>

<TextEditor languageId={{tab}} text={{texts[tab]}} />
```

```
TextEditor = FC { props ->
  cm = useCodeMirror {
    //other properties
    onChange = {text, _ ->
      console.log("onChange(${props.languageId}, $text)")
    }
    value = props.text
  }

  // <div>, useRef(), etc. to make CodeMirror work
}
```

Now to the issue. When I change the tab, for example from `0: english` to `1: german`, the followint thing appers in the console:
```
onChange(0, "Gutten tag")
```
See, the id (0) does not correspond to passed text (german). How is this even possible?! I'm in no way a React expert, but shouldn't the passing of properties be atomic? Or are the props somehow freezed in the hook or something?

Can you help me with this?

Disclaimer: I'm writing the code in Kotlin/JS, and using so called wrappers around JS libraries, but they are just helping with type safety, so I guess this is not an issue (but it might).

**Comment by jaywcjlove** [comment]
@Pitel I don't think this is a good idea.

**Comment by Pitel** [comment]
I've solved by dropping your wrapper andf writing my own version, which (using `useEffect()`) creates brand new state each time language id changes.
