### ISSUE TITLE
使用react-chrome-extension-boilerplate开发浏览器插件时，在inject.js中引入后options无效

### ISSUE THREAD

**Issue by guanpengchn** [uiwjs/react-codemirror#21]
react-chrome-extension-boilerplate是一个用react开发谷歌浏览器插件的工具，其中inject.js能够在网页中嵌入脚本，我尝试使用react-codemirror，发现options的所有选项都不生效，我换了其他的react-codemirror发现是可以的，不知道感不感兴趣排查一下原因？

**Comment by jaywcjlove** [comment]
@guanpengchn 可有实例我调试一下

**Comment by guanpengchn** [comment]
@jaywcjlove 感谢老大，在这里，https://github.com/guanpengchn/react-chrome-extension-codemirror-demo

![image](https://user-images.githubusercontent.com/13995641/73667143-ca5d0800-46de-11ea-93fb-d351c6748470.png)

运行起来大概是上面的效果图，上面的codemirror是uiwjs/react-codemirror，可以看到options的配置没生效

**Comment by guanpengchn** [comment]
具体说明我在使用方法中写了
