### ISSUE TITLE
Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.

### ISSUE THREAD

**Issue by dungbv99** [uiwjs/react-codemirror#216]
I have a project using uiw/react-codemirror version 4.0.6
It is run okay until mid night yesterday, when I clone my project and re install it. When it start some thing wrong is happended like this picture
![Screenshot from 2021-11-06 14-59-31](https://user-images.githubusercontent.com/42971823/140602630-a34bcb22-add7-45bb-997e-6bc8c726e4c0.png)

I think some bug happend when you update new version confile with the codemirror  dependency. Can you check for me?
Thank you!

**Comment by dungbv99** [comment]
@jaywcjlove Hopefully you can check it for me . Error happend in this file : https://github.com/uiwjs/react-codemirror/blob/master/src/useCodeMirror.ts#L80

**Comment by jaywcjlove** [comment]
I see the error message, not the error caused by `codemirror`. @dungbv99

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/140602677-c78e82f9-7dd8-4f78-9088-6575ca4ad169.png)

@dungbv99

**Comment by dungbv99** [comment]
@jaywcjlove  sorry I have send wrong picture. I have updated this

**Comment by dungbv99** [comment]
@jaywcjlove Can you check again
![Screenshot from 2021-11-06 14-59-31](https://user-images.githubusercontent.com/42971823/140602698-5e8391e3-c62b-42a4-b588-544faf183cec.png)

**Comment by dungbv99** [comment]
![Screenshot from 2021-11-06 15-08-00](https://user-images.githubusercontent.com/42971823/140602843-1db14059-67c1-46ed-a784-c6f9e9711fd8.png)

I have check your code in IDE and something wrong like this @jaywcjlove

**Comment by dungbv99** [comment]
@jaywcjlove I have down grade uiw/code-mirror to version 3.2.7 and it is ok to run but something like color or code-mirror extension is not use. Hopefully when you update your live you can notice me to update new version.
Thank you.

**Comment by NguyenTruongThanh-74** [comment]
I have same problem. Did you solve this? @jaywcjlove @dungbv99

**Comment by NguyenTruongThanh-74** [comment]
![251712202_668068104160770_421219922328601016_n](https://user-images.githubusercontent.com/55273693/140608903-4a603e1b-3970-46e3-aefb-22c4b232ec6c.png)
I have tried to create a basic project with code mirror and an error still happened

**Comment by dungbv99** [comment]
@jaywcjlove  @NguyenTruongThanh-74  I have know this problem, when i run yarn add @uiw/react-codemirror --save or npm install @uiw/react-codemirror --save now it will install 1 node module in this package @uiw/react-codemirror so the duplicate is happened

**Comment by abc444873863** [comment]
I have the same problem. 
Hope it can be solved recently.

**Comment by jaywcjlove** [comment]
@dungbv99 upgrade `@uiw/react-codemirror` to `v4.2.3`

**Comment by jaywcjlove** [comment]
@abc444873863 @NguyenTruongThanh-74 Seems to be a dependency problem. upgrade `@uiw/react-codemirror` to `v4.2.3`

**Comment by dungbv99** [comment]
@jaywcjlove  okay let me try it

**Comment by dungbv99** [comment]
@jaywcjlove I have updated `@uiw/react-codemirror `to `v4.2.3` but the error is still happened due to the node_module in `/node_module/@uiw/react-codemirror/node_module/` is conflicted with `./node_module/@codemirror` when I use this to try extension.
My temporary solution is after run `npm install` I remove node_module in `@uiw/codemirror`:
- `rm -rf /node_module/@uiw/react-codemirror/node_module/`

But I think it is the temporary solution, can you check again?

**Comment by dungbv99** [comment]
@jaywcjlove I have check new version, The error is remove but the line number is disable.
I must remove `/node_module/@uiw/react-codemirror/node_module` to show line number.
Can you check again.
You can tried my easy test source to check this bug.
https://github.com/dungbv99/react-code-mirror-error

**Comment by dungbv99** [comment]
@abc444873863 you can run `rm -rf ./node_module/@uiw/react-codemirror/node_module` to temporary solve this problem

**Comment by jaywcjlove** [comment]
```bash
npm ls @codemirror/view
my-app@0.1.0 /Users/wangchujiang/git-project/@uiw/demo/react-code-mirror-error
├─┬ @codemirror/lang-javascript@0.19.3
│ ├─┬ @codemirror/autocomplete@0.19.6
│ │ ├─┬ @codemirror/tooltip@0.19.6
│ │ │ └── @codemirror/view@0.19.16 deduped
│ │ └── @codemirror/view@0.19.16 deduped
│ ├─┬ @codemirror/highlight@0.19.6
│ │ └── @codemirror/view@0.19.16 deduped
│ ├─┬ @codemirror/language@0.19.3
│ │ └── @codemirror/view@0.19.16 deduped
│ ├─┬ @codemirror/lint@0.19.3
│ │ ├─┬ @codemirror/gutter@0.19.5
│ │ │ └── @codemirror/view@0.19.16 deduped
│ │ ├─┬ @codemirror/panel@0.19.0
│ │ │ └── @codemirror/view@0.19.16 deduped
│ │ └── @codemirror/view@0.19.16 deduped
│ └── @codemirror/view@0.19.16
└─┬ @uiw/react-codemirror@4.2.3
  ├─┬ @codemirror/basic-setup@0.19.0
  │ ├─┬ @codemirror/closebrackets@0.19.0
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/commands@0.19.5
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/comment@0.19.0
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/fold@0.19.1
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/history@0.19.0
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/matchbrackets@0.19.3
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/rectangular-selection@0.19.1
  │ │ └── @codemirror/view@0.19.16 deduped
  │ ├─┬ @codemirror/search@0.19.2
  │ │ └── @codemirror/view@0.19.16 deduped
  │ └── @codemirror/view@0.19.16 deduped
  ├─┬ @codemirror/theme-one-dark@0.19.1
  │ └── @codemirror/view@0.19.16 deduped
  └── @codemirror/view@0.19.15
```

~~`@codemirror/view@0.19.15`~~ => `@codemirror/view@0.19.16`

@dungbv99 This is a problem caused by version locking.

**Comment by jaywcjlove** [comment]
@dungbv99 Upgrade `@uiw/react-codemirror@4.2.4`

**Comment by karlhorky** [comment]
We fixed this in our application by adding a [Yarn Resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force a single version of `@codemirror/state` (actually, we already had resolutions of a lot of other CodeMirror packages too, to fix similar breakages):

```json
{
  "resolutions": {
    "@codemirror/highlight": "0.19.7",
    "@codemirror/lang-javascript": "0.19.7",
    "@codemirror/state": "0.19.9",
    "@codemirror/view": "0.19.47"
  }
}
```

**Comment by shubhendusaurabh** [comment]
I was having the same problem due to @codemirror/stream-parser being archived. now StreamParser must be imported from @codemirror/language

@jaywcjlove please update the readme.

**Comment by jaywcjlove** [comment]
@shubhendusaurabh Welcome to submit PR

**Comment by arvigeus** [comment]
I get it too with latest version. Actually even my current version which is deployed and working does not work on my laptop. What a mess... :/

**Comment by karlhorky** [comment]
In case you use npm and not Yarn, [npm 8.3+ has Overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (a similar feature to Yarn Resolutions). It should work similarly to [what I posted above](https://github.com/uiwjs/react-codemirror/issues/216#issuecomment-1070575028), but just use the key `"overrides"` instead of `"resolutions"` in your `package.json`.

Would be super interested if this works for you!

**Comment by arvigeus** [comment]
Works like a charm, thank you, @karlhorky !

**Comment by guillaume-leo** [comment]
I had this error today by using codemirror with AlpineJs... I tried the resolution solution but I get these errors then 

`warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.0"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.0"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.0"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.2"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.0"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"
warning Resolution field "@codemirror/view@0.19.47" is incompatible with requested version "@codemirror/view@^0.20.0"
warning Resolution field "@codemirror/state@0.19.9" is incompatible with requested version "@codemirror/state@^0.20.0"`

**Comment by karlhorky** [comment]
Yeah, these warnings (they are not errors but warnings) can happen if you use a version incompatible with the version requested by your dependencies.

But they are just warning you about potential incompatibilities, the new versions seem to work fine with `@uiw/react-codemirror` so far (in my testing)

**Comment by indicozy** [comment]
For me, I used two components:

import CodeMirror from '@uiw/react-codemirror';
import { Sandpack } from '@codesandbox/sandpack-react';
And because of that I had the same issue. I’ve decided to try out pnpm instead of npm and it somehow resolved the issue!

You can find more here: https://discuss.codemirror.net/t/troubleshooting-article-for-cm6/2803/13

**Comment by guillaume-leo** [comment]
> Yeah, these warnings (they are not errors but warnings) can happen if you use a version incompatible with the version requested by your dependencies.
> 
> But they are just warning you about potential incompatibilities, the new versions seem to work fine with `@uiw/react-codemirror` so far (in my testing)

Yes indeed they are just warnings, but then if I run the project I have a lot of 'No matching export ' errors and then crash...

Then I tried to use pnpm instead of  npm or yarn as suggested above, and the original error came back...

That's really annoying  can someone can share a working packages.json with me? If I understand correctly if I use correct versions of each packages it should work properly no?

**Comment by guillaume-leo** [comment]
By the way, I'm using vite, could it be related?

**Comment by nimatrazmjo** [comment]
Guys, I am trying to use `php` it give me this error:

```
import CodeMirror from '@uiw/react-codemirror';
// import { javascript } from '@codemirror/lang-javascript';
import { php } from '@codemirror/lang-php';
import { EditorView } from "@codemirror/view";
export default ({ changeHandler, ...otherProps }) => (
  <CodeMirror
    onChange={changeHandler}
    extensions={[php()]}
    {...otherProps}
  />
)
```
<img width="1003" alt="Screen Shot 2022-06-22 at 9 14 19 PM" src="https://user-images.githubusercontent.com/3712526/175092157-344e64fc-c0a0-4517-b9e4-b7349aeb831c.png">

**Comment by jaywcjlove** [comment]
@nimatrazmjo Dependency versions must be consistent. check it out with `npm ls @codemirror/view`

**Comment by nimatrazmjo** [comment]
Thank you @jaywcjlove, it was versioning issue

**Comment by wr8tt5** [comment]
I have this `Uncaught Error: Unrecognized extension value ...` error in an `electron` project and have not been able to resolve it. I first encountered it when using [codemirror-languageserver](https://github.com/FurqanSoftware/codemirror-languageserver) and worked around it by bringing its source code into my project. That is back on `@codemirror/...@0.20.0`. It's now been brought to my attention that this issue appears again when upgrading to `@codemirror/...@6.x.x`. I have a minimal example at [codemirror-languageserver-issue15](https://github.com/wr8tt5/codemirror-languageserver-issue15) that can be used to reproduce the issue. The work around this time is to update `package.json` to pin `@uiw/react-codemirror` to `4.8.1` i.e.
```
"dependencies": {
  "@uiw/react-codemirror": "4.8.1",
  ...
}
```
If It is changed to `4.9.0` or higher the issue arises, but I cannot see anything obvious that has caused this between the `v4.8.1` and `v4.9.0` tags.
I originally raised this issue against the `codemirror-languageserver` repo [here](https://github.com/FurqanSoftware/codemirror-languageserver/issues/15) where some further background information can be found. I have not been able to reproduce this on a normal browser (non-`electron`) project. Any help would be appreciated.

**Comment by hodasalah** [comment]
### Hello ,did any one face this bug with react 18 please i down grade the @ui/react-codemirror to 3.2.1  ii gone but i faced another bug duplicated codemirror component

**Comment by Alaboudi1** [comment]
I still get the error with most updated deps 
```
"dependencies": {
    "@codemirror/lang-javascript": "^6.1.0",
    "@uiw/react-codemirror": "^4.12.4",
    ...
  },
  "overrides": {
    "@codemirror/highlight": "0.19.8",
    "@codemirror/lang-javascript": "^6.1.0",
    "@codemirror/state": ">=6.0.0",
    "@codemirror/view": ">=6.0.0"
  },
```

**Comment by jaywcjlove** [comment]
@dungbv99 

~~`@codemirror/highlight`~~

> As of 0.20.0, this package has been split between @lezer/highlight and @codemirror/language

**Comment by just-Bri** [comment]
Why is this issue marked as closed?
I'm seeing this error when trying to run a unit test with vitest+testing-library/react.

I've tried every suggestion I've seen so far, things like locking packages to old version and manually installing specific codemirror deps.

**Comment by jaywcjlove** [comment]
@karlhorky You can provide an example that reproduces the error and I'll take a look at it for you.

**Comment by jaywcjlove** [comment]
The normal reason is a dependency version problem. Upgrade `@codemirror/*` to `v6+`

**Comment by karlhorky** [comment]
I think you meant to tag @kmacoders, right?

**Comment by TurtIeSocks** [comment]
Seeing this issue now after updating to latest

Broken with:
```
    "@codemirror/lang-json": "^6.0.1",
    "@codemirror/lint": "^6.1.0",
    "@uiw/react-codemirror": "^4.19.1",
```

Working with:
```
    "@codemirror/lang-json": "^6.0.1",
    "@codemirror/lint": "^6.1.0",
    "@uiw/react-codemirror": "4.11.6",
```

I tried it with every minor version between `4.12.*` and `4.19.*` and received the error on all of them.

Implementation:
```jsx
export function Code({ code, setCode }: Props) {
  const extensions = React.useMemo(
    () => [json(), linter(jsonParseLinter())],
    [],
  )

  return (
    <ReactCodeMirror
      extensions={extensions}
      theme="light"
      value={code}
      onUpdate={(value) => {
        if (value.docChanged) {
          setCode(value.state.doc.toString())
        }
      }}
    />
  )
}
```
Let me know if any other information would be helpful!

**Comment by tensed** [comment]
@vadimcoder Thanks! Reinstalling after following these steps seems to do the trick!

**Comment by vleborgne** [comment]
Hello, I fixed it by adding an alias in my webpack configuration
` alias: {
        '@codemirror/state': __dirname + '/node_modules/@codemirror/state/dist/index.cjs',
  },`

**Comment by jesse-r-s-hines** [comment]
In my case with webpack + typescript changing `tsconfig.json` `module` from `commonjs` to `es2020` was the only thing that fixed the issue.  (see https://github.com/codemirror/dev/issues/528)

**Comment by chatterbox777** [comment]
> In my case with webpack + typescript changing `tsconfig.json` `module` from `commonjs` to `es2020` was the only thing that fixed the issue. (see [codemirror/dev#528](https://github.com/codemirror/dev/issues/528))

You are my hero man, only this stuff helps... thnak you !

**Comment by yogiduzit** [comment]
I am getting the same error but while testing my CodeEditor component with Vitest. Any suggestions?

**Comment by SpaceCowboy326** [comment]
I am also seeing this issue with `@uiwjs/react-codemirror` and `vitest`. This _only_ happens when running tests, I have not seen the error in dev/production. I have a very minimal reproduction here:

[https://github.com/SpaceCowboy326/react-codemirror-vitest](https://github.com/SpaceCowboy326/react-codemirror-vitest)

Just run `npm run test` and it should fail with the error message in the thread description.

**Comment by somecho** [comment]
I'm also seeing this issue with `@uiwjs/react-codemirror v4.20.0` and `vitest v0.31.1`. I am using `@testing-library/react v14.0.0` to render a component with Codemirror. My CodeMirror component is using the `@nextjournal/lang-clojure v1.0.0` plugin.

**Comment by jaywcjlove** [comment]
@somecho https://discuss.codemirror.net/t/error-multiple-instances-of-codemirror-state/5174/2 looks unsolvable

**Comment by prmichaelsen** [comment]
> I had the same problem and this helped me:
> 
>     1. remove any direct dependencies on raw codemirror (if any) (I have yarn):
>        `yarn remove codemirror`
> 
>     2. `rm -fr yarn.lock`
> 
>     3. `rm -fr node_modules`
> 
>     4. `yarn install`


For posterity, this is the solution that worked for me. Specifically, `minimalSetup` and `basicSetup` are now functions.

**Comment by josephrocca** [comment]
Just playing around with a very basic hello world via URL imports, and ran into this problem. Downgrading `theme-one-dark@6.1.2` to `6.1.1` fixed it for me. Here's a minimal reproduction in case a dev here wants to take a look:
```html
<script type="module">
  import {EditorState} from "https://cdn.jsdelivr.net/npm/@codemirror/state@6.2.1/+esm";
  import {EditorView, keymap} from "https://cdn.jsdelivr.net/npm/@codemirror/view@6.19.0/+esm";

  // upgrading this to `6.1.2` causes this: "Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks"
  import { oneDark } from "https://cdn.jsdelivr.net/npm/@codemirror/theme-one-dark@6.1.1/+esm";

  let startState = EditorState.create({
    doc: "Hello World",
    extensions: [
      oneDark,
    ],
  });

  let view = new EditorView({
    state: startState,
    parent: document.body,
  });
</script>
```
(if URL imports like this aren't generally supported, then that's just tragic imo - makes it hard to play around with e.g. codepen/jsbin, create little demos, etc.)

**Comment by karlhorky** [comment]
> We fixed this in our application by adding a [Yarn Resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force a single version of `@codemirror/state` (actually, we already had resolutions of a lot of other CodeMirror packages too, to fix similar breakages):

Building on [my comment above](https://github.com/uiwjs/react-codemirror/issues/216#issuecomment-1070575028), if you are also using [`@mischnic/json-sourcemap`](https://www.npmjs.com/package/@mischnic/json-sourcemap), which [uses an outdated version of `@lezer/common` and `@lezer/lr`](https://github.com/mischnic/json-sourcemap/issues/1) and also [Renovate Bot](https://docs.renovatebot.com/) or similar to upgrade your dependencies, then you can guide Yarn Resolutions to choose the right versions like this:

```json
{
  "resolutions": {
    "**/@mischnic/json-sourcemap/@lezer/common": "0.15.12",
    "**/@mischnic/json-sourcemap/@lezer/lr": "0.15.8",
    "**/@codemirror/autocomplete/@lezer/common": "1.1.0",
    "**/@codemirror/commands/@lezer/common": "1.1.0",
    "**/@codemirror/lang-javascript/@lezer/common": "1.1.0",
    "**/@codemirror/language/@lezer/common": "1.1.0",
    "**/@codemirror/language/@lezer/lr": "1.3.11"
  }
}
```

Otherwise, the automatic dependency version upgrades from the bots will cause CodeMirror to break - eg. by losing syntax highlighting.

**Comment by vithalreddy** [comment]
any one using pnpm and next.js following solution worked for me

```
rm -rf node_modules pnpm-lock.yaml
rm -rf .next
pnpm i
```

**Comment by RajkiranJogu** [comment]
Hi,
I am getting the same error with the latest [4.21.21](https://www.npmjs.com/package/@uiw/react-codemirror/v/4.21.21) and @codemirror/lang-sql 6.5.5.


Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks


Is there any real fix for this issue?
@jaywcjlove

**Comment by grzegorzDlugokecki** [comment]
@RajkiranJogu were You able to solve that issue?

**Comment by gDlugokecki** [comment]
@RajkiranJogu Were you able to solve it? Got the same issue ;/

**Comment by joshparolin** [comment]
> Hello, I fixed it by adding an alias in my webpack configuration ` alias: { '@codemirror/state': __dirname + '/node_modules/@codemirror/state/dist/index.cjs', },`

React 18 + Webpack 5. Very basic setup. The webpack alias trick was the only thing that worked for me.

```
    "@codemirror/lang-html": "^6.4.8",
    "@uiw/react-codemirror": "^4.21.25",

---

import CodeMirror from "@uiw/react-codemirror";
import { html } from "@codemirror/lang-html";

...

<CodeMirror
              value={customHtml}
              height="200px"
              extensions={[html()]}
              onChange={value => {
                setCustomHtml(value);
              }}
            />
```

**Comment by yogiduzit** [comment]
I was able to solve it using `vitest` by adding the following lines
```
alias: {
  '@codemirror/state': path.resolve(
    __dirname,
    './node_modules/@codemirror/state/dist/index.cjs'
  ),
  '@codemirror/lang-yaml': path.resolve(
    __dirname,
  ),
  '@codemirror/lang-json': path.resolve(
    __dirname,
    './node_modules/@codemirror/lang-json/dist/index.cjs'
  )
}
```
Basically, you need to force the CJS version of `@codemirror/state` and all other packages depending on it.

**Comment by uds214125** [comment]
Ultimately, If you are using vite as project build tool, you should use these configuration, 

```
// vite.config.js
import { defineConfig } from 'vite';
import path from "path";

export default defineConfig({
    optimizeDeps: {     
      include: ['@codemirror/state', '@codemirror/view'],
    },
    resolve: {
        alias: {
            '@codemirror/state': path.resolve(
              __dirname,
              './node_modules/@codemirror/state/dist/index.cjs'
            ),
            '@codemirror/lang-yaml': path.resolve(
              __dirname,
            ),
            '@codemirror/lang-json': path.resolve(
              __dirname,
              './node_modules/@codemirror/lang-json/dist/index.cjs'
            )
          }
    },
  })
```

**Comment by josuenm** [comment]
If anyone is still having a problem, try this:

vite.config.ts
``` js
export default defineConfig(async () => ({
  resolve: {
      alias: {
        '@codemirror/state': path.resolve(__dirname, 'node_modules/@codemirror/state/dist/index.cjs'),
      }
  }
}));
```

**Comment by aspiers** [comment]
See https://github.com/uiwjs/react-codemirror/issues/613#issuecomment-2544272857 and https://github.com/uiwjs/react-codemirror/issues/680#issuecomment-2544279514 for a proposed proper fix.

**Comment by ketgg** [comment]
Had same isse this helped (I am using yarn):
1. `rm -rf node_modules`
2. `rm -rf yarn.lock`
3. `yarn install`
