### ISSUE TITLE
get access to the original cm

### ISSUE THREAD

**Issue by mbui0327** [uiwjs/react-codemirror#226]
I wonder how can I get access to the `cm` that is mentioned in CodeMirror document.
So I can run something like `cm.getCursor()`. Currently, it seems like this package only expose `StateView` and `EditorView`.
Thanks.

**Comment by jaywcjlove** [comment]
Then you need to use the old [v3](https://github.com/uiwjs/react-codemirror/tree/v3) version
@mbui0327

**Comment by mbui0327** [comment]
I see.Any suggestion on how best to get the event such as the change event here https://codemirror.net/doc/manual.html#events.
I know that I can use `onChange`. But this will give me `ViewUpdate`, which does not seem to be well documented.
Thanks.

**Comment by jsjoeio** [comment]
I was wondering this as well as I'd like to be able to do this: https://github.com/replit/codemirror-vim/issues/6#issuecomment-1009362883

Is there a plan to implement a way to access the CodeMirror instance in the latest version of react-codemirror?

**Comment by jaywcjlove** [comment]
https://codesandbox.io/s/react-codemirror-example-codemirror-6-forked-m0ibd?file=/src/App.js

@jsjoeio Is that so?

```jsx
import React, { useEffect, useRef } from "react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { vim, Vim } from "@replit/codemirror-vim";

export default function App() {
  const cmRef = useRef();
  useEffect(() => {
    setTimeout(() => {
      console.log("--2>", cmRef.current);
      Vim.exitInsertMode(
        cmRef.current.view.cm
        // (cmRef.current.view as any).cm
      );
      // Vim.handleKey((view as any).cm, "<Esc>");
    }, 3000);
  }, []);
  return (
    <CodeMirror
      ref={cmRef}
      value="console.log('hello world!');"
      height="200px"
      extensions={[javascript({ jsx: true }), vim()]}
      onChange={(value, viewUpdate) => {
        console.log("value:", value);
      }}
    />
  );
}
```

**Comment by jsjoeio** [comment]
Wow! @jaywcjlove you made that look so easy! Exactly what I was looking for. I found I can also do it with `viewUpdate` inside the `onChange` function with `viewUpdate.view.cm`. 

Thank you very much!
