### ISSUE TITLE
How to turn on lineWrapping?

### ISSUE THREAD

**Issue by emilevirus** [uiwjs/react-codemirror#228]
Is there any way to turn on lineWrapping as the options attribute is gone?

**Comment by jaywcjlove** [comment]
@emilevirus I am not sure how to do this.

**Comment by emilevirus** [comment]
Found it. Had to use EditorView.lineWrapping as extension

**Comment by syssecfsu** [comment]
@emilevirus Could you please provide more information on how to do that? I could not figure out how to set EditorView.lineWrapping. Thank you!
