### ISSUE TITLE
Change cursor start position?

### ISSUE THREAD

**Issue by jsjoeio** [uiwjs/react-codemirror#243]
Hi! Thanks for making this library.

Is there a way to change where the cursor starts? I tried creating an `EditorState` with a `selection` value but that didn't seem to do it:

https://codesandbox.io/s/react-codemirror-example-codemirror-6-hook-forked-zc7d4?file=/src/App.js

**Comment by jsjoeio** [comment]
I cannot seem to get `view` or `state` in the `useCodeMirror` hook to work. What am I doing wrong?

```jsx
const defaultView = new EditorView({
  state: EditorState.create({
    doc: `hello world!
who doesn't love relative line numbers?`,
    extensions: [vim(), lineNumbersRelative()],
    selection: EditorSelection.cursor(5),
    parent: document.querySelector("#editor")
  })
});

export default function App() {
  const editor = useRef();
  const { setContainer, view } = useCodeMirror({
    view: defaultView,
    container: editor.current
  });
  useEffect(() => {
    if (editor.current) {
      setContainer(editor.current);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editor.current]);
  return (
    <div>
      <div id="editor" ref={editor} />
    </div>
  );
}
```

https://codesandbox.io/s/react-codemirror-example-codemirror-6-hook-forked-issue243-zc7d4

**Comment by jsjoeio** [comment]
Nevermind, I think TypeScript was showing me the wrong props for some reason. After looking under the hood, I saw `selection`. 

Got it working :D 

```jsx
  const { setContainer } = useCodeMirror({
    autoFocus: true,
    selection: EditorSelection.cursor(5),
    container: editor.current,
    extensions: [vim(), lineNumbersRelative(), javascript()],
    value: code
  });
```

https://codesandbox.io/s/react-codemirror-example-codemirror-6-hook-forked-issue243-attempt-2-uyjdy?file=/src/App.js

**Comment by Qodestackr** [comment]
```js
  const { setContainer } = useCodeMirror({
    autoFocus: true,
    selection: EditorSelection.cursor(0),
    container: editor.current,
    extensions: [vim()/**, lineNumbersRelative() */, javascript()],
    value: code
  });
 ```
 
 Took some of your code, but cursor never appears at the start? @jsjoeio

**Comment by jsjoeio** [comment]
@Qodestackr did you try the codesandbox linked there? just tried and it works

<img width="1392" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/3806031/2a5be5ba-7dad-48e3-b2c2-1ee1093da78f">

**Comment by Qodestackr** [comment]
Thanks,
