### ISSUE TITLE
How to use `Extensions` prop fully?

### ISSUE THREAD

**Issue by ShafSpecs** [uiwjs/react-codemirror#248]
Hello, thx for this awesome package. I am building an editor and I have come across the `extensions` prop which I don't quie understand. The official codemirror docs has done nothing but confuse me more? Could you perhaps explain it a bit more in the docs?

**Comment by jaywcjlove** [comment]
https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=%40codemirror%2Fview&page=1&configure%5BhitsPerPage%5D=12

@ShafSpecs  There are some good learning methods. Learn through examples and official documents.

![image](https://user-images.githubusercontent.com/1680273/148679556-561a0594-8f84-444c-bf09-2608b2f95e21.png)
