### ISSUE TITLE
Particular lines readonly

### ISSUE THREAD

**Issue by andrebnassis** [uiwjs/react-codemirror#259]
Is there any **sample** that shows how to set **some lines** as **readonly**, so it can't be edited?

I found something related to markText and beforeChange, but I couldn't solve it yet using _@uiw/react-codemirror_ package. 

https://stackoverflow.com/questions/17415100/codemirror-particular-lines-readonly

Thanks in advance! 

PS: If possible, use the getting started sample as base and set only the first line as readonly:

```typescript
import CodeMirror from '@uiw/react-codemirror';
import { javascript } from '@codemirror/lang-javascript';

const CodeEditor = () => {
  
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[javascript({ jsx: true })]}
      onChange={(value, viewUpdate) => {
        console.log('value:', value);
        console.log(viewUpdate);
      }}
      theme={'dark'}
    />
  );
}

export default CodeEditor;
```

**Comment by jaywcjlove** [comment]
https://stackoverflow.com/a/17482204/1334703

This is the solution from the previous version. 

You can try it with [v3](https://github.com/uiwjs/react-codemirror/tree/v3).

CodeMirror v6 used by `@uiw/react-codemirror@v4`

**Comment by andrebnassis** [comment]
> https://stackoverflow.com/a/17482204/1334703
> 
> This is the solution from the previous version. 
> 
> You can try it with [v3](https://github.com/uiwjs/react-codemirror/tree/v3).
> 
> CodeMirror v6 used by `@uiw/react-codemirror@v4` 
> 

Thanks for the response, but I would like to start using the latest version.

If someone has any example of implementing this feature I would be very glad.

**Comment by raquelhortab** [comment]
Hi! I am also interested in this. I cannot seem to understand how to use options in codemirror docs for the component version, is there any tutorial about that? How would [these options ](https://codemirror.net/doc/manual.html#api_marker)be applied (markText for instance), or how can we use [codemirror configuration](https://codemirror.net/doc/manual.html#config)? (readOnly for instance, it's not working through props)

**Comment by simpsonphile** [comment]
i would like to know too how to block particular lines from editing

**Comment by raquelhortab** [comment]
> and update how to do it in v4?

[#108](https://github.com/uiwjs/react-codemirror/issues/108#issuecomment-1040115371) 

it looks like the only way is to downgrade, it's weird that newer versions have fewer functionalities, maybe they'll add it in the future? I don't know but afterall, it's an opensource library so I do appreciate whatever they can offer

**Comment by jaywcjlove** [comment]
@simpsonphile [Migrate from @uiw/react-codemirror v3 to v4](https://github.com/uiwjs/react-codemirror/issues/88#issuecomment-914185563).
- https://github.com/uiwjs/react-codemirror/issues/88#issuecomment-914185563

**Comment by andrebnassis** [comment]
I just released an extension that easy allow to work with read-only ranges on CodeMirror6.
For anyone who is interested on the solution:

package: https://www.npmjs.com/package/codemirror-readonly-ranges

full documentation: https://andrebnassis.github.io/codemirror-readonly-ranges/?path=/story/0-introduction--page

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/how-to-make-certain-ranges-readonly-in-codemirror6/3400/5

```js
function readOnlyTransactionFilter() {
  return EditorState.transactionFilter.of((tr) => {
    let readonlyRangeSet = tr.startState.field(underlineField, false)
    if (readonlyRangeSet && tr.docChanged && !tr.annotation(Transaction.remote)) {
      let block = false
      tr.changes.iterChangedRanges((chFrom, chTo) => {
        readonlyRangeSet.between(chFrom, chTo, (roFrom, roTo) => {
          if (chTo > roFrom && chFrom < roTo) block = true
        })
      })
      if (block) return []
    }
    return tr
  }
}
```
