### ISSUE TITLE
Is there a bundled version of the component?

### ISSUE THREAD

**Issue by raquelhortab** [uiwjs/react-codemirror#267]
Hi, I was wondering if there is any way I can use this component by importing a bundled version via a script tag (to be used with react-dom). The thing is I am not using node but a really old version of ruby on rails and I need to use the .js versions of react components.

**Comment by raquelhortab** [comment]
Looks like it! trying it first thing tomorrow, thank you very much!

**Comment by raquelhortab** [comment]
Yes that is what I was looking for, thank you very much !

**Comment by raquelhortab** [comment]
@jaywcjlove how should I use language modes with the bundled version?

if I need to use:
`extensions={[javascript({ jsx: true })]}`

I am guessing I need a bundled version of the javscript extension as well? I do have a javascript.js file that works with the conventional Codemirror editors, but that one only defines an editor mode, I am not sure it's the same as the npm version.

**Comment by jaywcjlove** [comment]
@raquelhortab You need the bundled version of the **javascript extension**.

**Comment by jaywcjlove** [comment]
@raquelhortab  I looked at the official example and made changes that should meet your needs.
https://codepen.io/jaywcjlove/pen/podWJra?editors=0010

Example: 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <script src="https://unpkg.com/react@16.x/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16.x/umd/react-dom.development.js" crossorigin></script>
  <script src="https://codemirror.net/6/codemirror.js"></script>
  <script src="https://unpkg.com/@uiw/react-codemirror@4.4.1/dist/codemirror.min.js"></script>
</head>
<body>
  <div id="container" style="padding: 24px"></div>
  <script>
    const {javascript} = CM["@codemirror/lang-javascript"];
    const ReactCodeMirror = codemirror.default;
    const e = React.createElement;
    const Demo = () => {
      return e(
        'div', {},
        e(ReactCodeMirror, {
          value: console.log('hello world!'),
          height: '200px',
          extensions: [javascript({ jsx: true })],
          onChange: (value, viewUpdate) => {
            console.log('value:', value);
          }
        })
      );
    }

    ReactDOM.render(
      e(Demo),
      document.getElementById("container")
    );

  </script>
</body>
</html>
```

**Comment by raquelhortab** [comment]
@jaywcjlove 

Wow that is fantastic, it'll be very useful, thank you very much for the effort and time!
