### ISSUE TITLE
How to enable word wrap?

### ISSUE THREAD

**Issue by max-programming** [uiwjs/react-codemirror#274]
Right now the editor just expands itself when the code is more in one line. If we set a max width, it has a scrollbar.

Is there a workaround to enable word wrap in the editor?

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/making-codemirror-6-respect-indent-for-wrapped-lines/2881/2

Maybe [issue](https://discuss.codemirror.net/t/making-codemirror-6-respect-indent-for-wrapped-lines/2881/2) can help you.

@max-programming

**Comment by jaywcjlove** [comment]
@max-programming 

```diff
import React from "react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
+ import { EditorView } from "@codemirror/view";

export default function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[
         javascript({ jsx: true }), 
+         EditorView.lineWrapping
      ]}
      onChange={(value, viewUpdate) => {
        console.log("value:", value);
      }}
    />
  );
}
```

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/228#issuecomment-1057144653
