### ISSUE TITLE
How to use methods from programming api

### ISSUE THREAD

**Issue by hussamkhatib** [uiwjs/react-codemirror#288]
https://codemirror.net/doc/manual.html#api

**Comment by jaywcjlove** [comment]
`@uiw/react-codemirror@v4+` use [codemirror 6](https://codemirror.net/6/).

@hussamkhatib

**Comment by jaywcjlove** [comment]
You can look at the documentation for v3. https://github.com/uiwjs/react-codemirror/tree/v3

**Comment by hussamkhatib** [comment]
thanks !!
I'm assuming features mentioned in this branch works in the master branch (i.e it would probally be published by master branch)
