### ISSUE TITLE
V3 : fake line at the end

### ISSUE THREAD

**Issue by thib3113** [uiwjs/react-codemirror#289]
Hello, I came here, because after days of search, and didn't find a solution . 

First, I'm locked with v3, because the language I need seems not supported by CM6 ( handlebars ) . 

At the end of the editor, it always add a "fake" line ( like on your demo, https://raw.githack.com/uiwjs/react-codemirror/doc3/index.html ) .

Codemirror demos seems to doesn't include this bug, and neither react-cm V4 . 

Did you have any idea ? ( I tryed multiple settings / debugging CM a little / clone this component to try ). 

---

It seems to be linked to the css file ... trying to use directly the css from codemirror (forking this component, removing css, and including codemirror css), seems to resolve the problem

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-codemirror-v3-vgr4n?fontsize=14&hidenavigation=1&theme=dark

I didn't find a "fake" problem. @thib3113

**Comment by thib3113** [comment]
@jaywcjlove in you example, can you scroll on the editor ?

Me, I can ( I scroll a little to show it ) :
![image](https://user-images.githubusercontent.com/5489218/159879562-d46d7a03-0193-4518-9acd-25a891db6036.png)

And so, I can totally hide the line : 
![image](https://user-images.githubusercontent.com/5489218/159879669-db8b84c2-dc2b-4849-8d85-774cdd4ee44b.png)


It seems to add a "line", at the bottom of the others lines . And count it in the scroll .

So, If I got only one line, I can totally hide it .

**Comment by zkdev** [comment]
experience same behaviour on Firefox `103.0.2`, any updates?

**Comment by jaywcjlove** [comment]
Upgrade `v3.2.9`

@zkdev @thib3113

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-codemirror-v3-vgr4n?fontsize=14&hidenavigation=1&theme=dark

**Comment by zkdev** [comment]
great fixed it, thank you!
