### ISSUE TITLE
unable to use doc.method for content manipulation

### ISSUE THREAD

**Issue by hussamkhatib** [uiwjs/react-codemirror#290]
Hi, I am using the v3.2.7 version of this package.
The reason I am not using the latest is that it does not have props to do advanced stuff.
 
```
const handleOnBeforeChange = (editor) => {
  console.log(editor.getDoc().getValue())   // logs out the text content in the editor 
  console.log(editor.getDoc().setValue("newValue"))  
  }

<CodeMirror onBeforeChange={handleOnBeforeChange} />
```
![image](https://user-images.githubusercontent.com/52914487/159960139-966f7c94-03f1-42bb-8968-1414be8b2108.png)

![image](https://user-images.githubusercontent.com/52914487/159958508-fc5d6fbf-2ba8-439f-b9d4-d05bd94cf1fc.png)
https://codemirror.net/doc/manual.html#api_content

is there any other alternative ways to tackle this problem?
What I'm trying to achieve is to have an uncontrolled component whose values I will manipulate using code (methods like replaceRange, addWidget)

**Comment by jaywcjlove** [comment]
```diff
<CodeMirror
  value={code}
  onBeforeChange={(editor) => {
    console.log(editor.getDoc().getValue()); // logs out the text content in the editor
-    // console.log(editor.getDoc().setValue("newValue"))
    console.log(">>>>>");
  }}
  options={{
    theme: "monokai",
    keyMap: "sublime",
    mode: "jsx"
  }}
/>
```

@hussamkhatib

**Comment by jaywcjlove** [comment]
you need to use react state
@hussamkhatib
