### ISSUE TITLE
[Feature Request] Support 'readOnly'

### ISSUE THREAD

**Issue by wsw0108** [uiwjs/react-codemirror#295]
https://codemirror.net/6/docs/ref/#state.EditorState^readOnly
> Not to be confused with [EditorView.editable](https://codemirror.net/6/docs/ref/#view.EditorView%5Eeditable), which controls whether the editor's DOM is set to be editable (and thus focusable).

**Comment by jaywcjlove** [comment]
@wsw0108 Need to provide a readOnly props? EditorView.editable used wrong?

**Comment by wsw0108** [comment]
@jaywcjlove Add a prop 'readOnly' should be ok. Thanks.

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/codemirror-6-readonly-editor/3930/2

```js
EditorState.readOnly.of(true)
```

```jsx
import CodeMirror from '@uiw/react-codemirror';

export default function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[EditorState.readOnly.of(true)]}
      onChange={(value, viewUpdate) => {
        console.log('value:', value);
      }}
    />
  );
}
```

**Comment by jaywcjlove** [comment]
@wsw0108 Upgrade `@uiw/react-codemirror@4.6.0`

**Comment by wsw0108** [comment]
Oh, there is `EditorState.readOnly.of(true)`.

`readOnly` props also ok. Thanks again.
