### ISSUE TITLE
index.tsx:126 Uncaught Error: value must be typeof string but got object

### ISSUE THREAD

**Issue by vsumit89** [uiwjs/react-codemirror#297]
```
        <CodeMirror
          value="{}"
          height="100%"
          theme={oneDark}
          extensions={[jsonLanguage]}
          onChange={(value, viewUpdate) => {  
            console.log({ value })
          }}
        />
```
I have the above component embedded in antd Form.Item. It is giving me the error in title. I am using react version 16.13. When I use the same component on react 18 it works fine.

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-fphdmw?fontsize=14&hidenavigation=1&theme=dark

@vsumit89 Not sure what is causing your problem, my example doesn't have a problem.

**Comment by vsumit89** [comment]
hey @jaywcjlove actually there was some problem in variable binding on my end. The issue is solved, Thanks.
