### ISSUE TITLE
Auto complete in code mirror

### ISSUE THREAD

**Issue by vsumit89** [uiwjs/react-codemirror#298]
How can I get autocomplete recommendation in code mirror

**Comment by jaywcjlove** [comment]
@vsumit89 You may need to study [codemirror 6](https://codemirror.net/6/examples/autocompletion/)'s documentation.

**Comment by thebpmgroup** [comment]
I don't really think that's an answer. I can read codemirror 6's documenation until the end of time, but it still won't guide me on how to get this working. This needs a trivial example with a basic stock of completions, and I would suggest adding this to the documentation.

**Comment by jaywcjlove** [comment]
The official documentation provides examples.

https://codemirror.net/6/examples/autocompletion/

**Comment by jaywcjlove** [comment]
https://codemirror.net/6/examples/autocompletion/

```jsx
import CodeMirror from '@uiw/react-codemirror';
import { javascript } from '@codemirror/lang-javascript';
import { autocompletion } from '@codemirror/autocomplete';

function myCompletions(context) {
  let word = context.matchBefore(/\w*/)
  if (word.from == word.to && !context.explicit)
    return null
  return {
    from: word.from,
    options: [
      {label: "match", type: "keyword"},
      {label: "hello", type: "variable", info: "(World)"},
      {label: "magic", type: "text", apply: "⠁⭒*.✩.*⭒⠁", detail: "macro"}
    ]
  }
}

export default function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[autocompletion({override: [myCompletions]})]}
      onChange={(value, viewUpdate) => {
        console.log('value:', value);
      }}
    />
  );
}
```

**Comment by thebpmgroup** [comment]
```extensions={[autocompletion({override: [myCompletions]})]}```

That's the magic right there

**Comment by jaywcjlove** [comment]
@thebpmgroup If you have an example, please share it, thx!

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/579#issuecomment-1732270138
