### ISSUE TITLE
Format code

### ISSUE THREAD

**Issue by lililo111** [uiwjs/react-codemirror#305]
How can I format code in codemirror?
Should I use the props -- extensions or anything else?

**Comment by lililo111** [comment]
And how would I get the codemirror native object and use native methods?
thanks if anyone could help.

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/code-formatting-in-code-mirror/3405/2

The author says this feature is not supported.
@lililo111

**Comment by arvigeus** [comment]
Check this out, I think it might be what you are looking for: https://github.com/arvigeus/format-code

**Comment by AurelianSpodarec** [comment]
Still not supported?
