### ISSUE TITLE
Spark SQL support

### ISSUE THREAD

**Issue by bdemirel** [uiwjs/react-codemirror#306]
According to [this issue](https://github.com/codemirror/CodeMirror/issues/6663), code mirror supports Spark SQL via a special mime type. How would that work with this project? Would I still need to build my own dialect for it using [@codemirror/lang-sql](https://github.com/codemirror/lang-sql)?

**Comment by jaywcjlove** [comment]
https://www.npmjs.com/package/@codemirror/legacy-modes/v/0.20.0#user-content-sql.sparksql

```jsx
import { StreamLanguage } from "@codemirror/stream-parser"
import { sparkSQL } from "@codemirror/legacy-modes/mode/sql"

export default function App() {
  return (
    <CodeMirror
      value="code "
      height="200px"
      extensions={[StreamLanguage.define(sparkSQL)]}
      onChange={(value, viewUpdate) => {
        console.log('value:', value);
      }}
    />
  );
}
```

@bdemirel

**Comment by bdemirel** [comment]
Yes, I was able to make this work after creating the issue. From what I can see, this only provides syntaxes highlighting, but that's because it's the only support, is that correct?

Is there any way to make the other features work?

**Comment by jaywcjlove** [comment]
@bdemirel You need to check the official documentation and encapsulate your own extension

https://codemirror.net/6/examples/

**Comment by bdemirel** [comment]
Thanks, I'll take a look!
