### ISSUE TITLE
Error in upgrade"@codemirror/lang-javascript"@6.0.0

### ISSUE THREAD

**Issue by xiaoyu-a** [uiwjs/react-codemirror#327]
Hello, I found error after upgrading `@codemirror/lang-javascript` to `6.0.0`.

You can reproduce with this demo. 

[Sandbox Demo](https://codesandbox.io/s/react-codemirror-example-codemirror-6-hook-forked-x1hq9s?file=/src/App.js)

![2022-06-09 11 16 02](https://user-images.githubusercontent.com/31204860/172756755-318271c8-3618-4db8-8109-b975fa26926d.png)

["@codemirror/lang-javascript" CHANGELOG](https://github.com/codemirror/lang-javascript/blob/main/CHANGELOG.md)

**Comment by jaywcjlove** [comment]
@xiaoyu-a  https://codesandbox.io/embed/react-codemirror-example-codemirror-6-uiwjs-react-codemirror-issues-327-forked-c4f223?fontsize=14&hidenavigation=1&theme=dark

```diff
-    "@codemirror/lang-javascript": "6.0.0",
+    "@codemirror/lang-javascript": "0.20.1",
```

**Comment by xiaoyu-a** [comment]
`@codemirror/lang-javascript` 6.0.0 is not supported now?

**Comment by jaywcjlove** [comment]
@xiaoyu-a Upgrade v4.8.0

https://codesandbox.io/embed/react-codemirror-example-codemirror-6-uiwjs-react-codemirror-issues-327-forked-c4f223?fontsize=14&hidenavigation=1&theme=dark
