### ISSUE TITLE
How to use with line-break?

### ISSUE THREAD

**Issue by alexandrsek** [uiwjs/react-codemirror#330]
Hello everyone! How to apply the line-break?

**Comment by jaywcjlove** [comment]
I do not understand what you mean.
@alexandrsek

**Comment by yannicka** [comment]
I think I am looking for a solution to the same problem.

The EditorView object allow a `lineWrapping` argument: https://codemirror.net/docs/ref/#view.EditorView.lineWrapping

How is it possible to set this parameter (and others similar options) to `true`?

**Comment by jaywcjlove** [comment]
@yannicka See example: https://codemirror.net/examples/config/#dynamic-configuration

**Comment by jaywcjlove** [comment]
```jsx
import React from "react";
import { EditorView } from "codemirror";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";

export default function App() {
  return (
    <div>
      <CodeMirror
        value="console.log('hello world!');"
        height="200px"
        theme={oneDark}
        extensions={[EditorView.lineWrapping, javascript({ jsx: true })]}
        onChange={(value, viewUpdate) => {
          console.log("value:", value);
        }}
      />
    </div>
  );
}
```

https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-7bgggy?fontsize=14&hidenavigation=1&theme=dark

@yannicka @alexandrsek 

https://discuss.codemirror.net/t/dynamically-change-linewrapping/3027/3

**Comment by alexandrsek** [comment]
Thanks! Thats exactly what I was looking for! Good luck!
