### ISSUE TITLE
Use vim mode

### ISSUE THREAD

**Issue by barreiros** [uiwjs/react-codemirror#331]
Hi!

Can I use keymap/vim? I've tried to pass the param keymap in multiples ways...

```
<CodeMirror 
  value={code} 
  onChange={setCode} 
  onViewChanged={setView} 
  options={{
    theme: 'monokai',
    keyMap: 'sublime',
    mode: 'jsx',
  }
}/>
```
```
<CodeMirror 
value={code} 
onChange={setCode} 
onViewChanged={setView} 
keymap="vim"
}/>
```

...but the browser returns 

`ReferenceError:` CodeMirror is not defined`

Thanks!

**Comment by jaywcjlove** [comment]
You can provide an example using [codesandbox.io](https://codesandbox.io/embed/react-codemirror-example-codemirror-6-slvju?fontsize=14&hidenavigation=1&theme=dark).

@barreiros

**Comment by jaywcjlove** [comment]
@barreiros example: https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-uby11k?fontsize=14&hidenavigation=1&theme=dark

```jsx
import React from "react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";

import { vim } from "@replit/codemirror-vim";

export default function App() {
  return (
    <div>
      <CodeMirror
        value="console.log('hello world!');"
        height="200px"
        theme="dark"
        extensions={[vim(), javascript({ jsx: true })]}
        onChange={(value, viewUpdate) => {
          console.log("value:", value);
        }}
        options={{
          keyMap: "vim"
        }}
      />
    </div>
  );
}

```

**Comment by barreiros** [comment]
Great!

Thanks, @jaywcjlove

**Comment by prmichaelsen** [comment]
is there anyway to disable 'esc' behavior blurring the editor. I know `C-c` works but a having to use two keys for a common use case is very "anti-vim"
