### ISSUE TITLE
How to create a mergeView editor

### ISSUE THREAD

**Issue by 1pone** [uiwjs/react-codemirror#343]
I find a demo on codeMirror v5 about [mergeView](https://codemirror.net/5/doc/manual.html#addon_merge), but how to create a mergeView editor with v6 or react-codemirror?
Thanks

**Comment by jaywcjlove** [comment]
@1pone https://discuss.codemirror.net/t/cm6-diff-merge-editor-example/4317

**Comment by 1pone** [comment]
Thansk
