### ISSUE TITLE
How to automatically track the scroll bar to the last line

### ISSUE THREAD

**Issue by pixiake** [uiwjs/react-codemirror#345]
I tried to use react-codemirror to write a page that automatically displays real-time logs.  But I found that scroll  can't automatically track the latest line. I can't find the relevant example, how should I set it ？ Thanks

**Comment by pixiake** [comment]
Thanks very much

**Comment by pixiake** [comment]
@jaywcjlove Hi，I tried to find any way to set `auto wrap`, but it didn't work.  Would you please provide an example ?  Thanks

**Comment by jaywcjlove** [comment]
@pixiake This is a new question(Issue). https://github.com/uiwjs/react-codemirror/issues/317#issuecomment-1168471146 may help you.

**Comment by jaywcjlove** [comment]
@pixiake https://github.com/uiwjs/react-codemirror/issues/274#issuecomment-1047488376

**Comment by jaywcjlove** [comment]
@pixiake 

```diff
import React from "react";
import CodeMirror from "@uiw/react-codemirror";
import { javascript } from "@codemirror/lang-javascript";
+ import { EditorView } from "@codemirror/view";

export default function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[
         javascript({ jsx: true }), 
+         EditorView.lineWrapping
      ]}
      onChange={(value, viewUpdate) => {
        console.log("value:", value);
      }}
    />
  );
}
```
