### ISSUE TITLE
Modify the viewport

### ISSUE THREAD

**Issue by RemiBrb** [uiwjs/react-codemirror#351]
How can i modify the [viewport](https://codemirror.net/docs/ref/#view.EditorView.viewport) from the [hook example](https://github.com/uiwjs/react-codemirror/issues/316#issuecomment-1159631781) ?

I tried through `extensions` or `setView` but without success. 
Is there any way ? Or should it be added in `BasicSetup` (as in [#316](https://github.com/uiwjs/react-codemirror/issues/316#issuecomment-1159631781)) ?

**Comment by jaywcjlove** [comment]
@RemiBrb Like this? https://codesandbox.io/embed/react-codemirror-example-codemirror-6-uiwjs-react-codemirror-issues-351-yr4vg?fontsize=14&hidenavigation=1&theme=dark
