### ISSUE TITLE
How to get the current cursor position?

### ISSUE THREAD

**Issue by arbob** [uiwjs/react-codemirror#352]
I want to get the current cursor position when I select a field from a dropdown in the form. Normally I'd do `ref.current.selectionStart` for text input. How can I emulate the same in react codemirror?

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/4ca295980751666cc1961cf47ec9cdebd25fe043/core/src/utils.ts#L42-L44

```js
view.state.selection.asSingle().main
```

```jsx
<CodeMirror
  value="console.log('hello world!');"
  height="200px"
  theme="dark"
  onStatistics={(data) => {
    console.log(data.selectionAsSingle);
  }}
  extensions={[javascript({ jsx: true })]}
  onChange={onChange}
/>
```

```jsx
<CodeMirror
  value="console.log('hello world!');"
  height="200px"
  theme="dark"
  ref={($ref) => {
    if ($ref && $ref.view) {
      console.log("$ref::", $ref.view.state.selection.main);
    }
  }}
  onStatistics={(data) => {
    console.log(data.selectionAsSingle);
  }}
  extensions={[javascript({ jsx: true })]}
  onChange={onChange}
/>
```

@arbob Exampel https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-wixg3f?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/1680273/177558568-6fe4c44e-4479-4ed6-b3f3-9c0135e61e28.png">

@arbob

**Comment by arbob** [comment]
![Screenshot 2022-07-07 at 3 55 36 PM](https://user-images.githubusercontent.com/40889313/177752496-c567d5fc-d38c-45c3-8300-60b4d44c48ae.png)
Although, `onStatistics` still doesn't exist, but your solution helped me a lot in finding a good enough solution. Thank you very much.

**Comment by zbysir** [comment]
> onStatistics doesn't exists on type. Also, custom `ref.current.state.selection.asSingle().main` return only range with no change in values.

Works if use `ref.current?.view?.state?.selection.asSingle()` instead of `ref.current?.state?.selection.asSingle()`.

looks like a bug.

**Comment by champion0122** [comment]
@jaywcjlove  onStatistics这个api是什么作用，想要监听光标的变化只能用这个api吗。现在想做一个根据光标移动获取当前方法名的功能，输入的时候会触发好几次onStatistics。烦请大佬解答

> https://github.com/uiwjs/react-codemirror/blob/4ca295980751666cc1961cf47ec9cdebd25fe043/core/src/utils.ts#L42-L44
> 
> ```js
> view.state.selection.asSingle().main
> ```
> 
> ```js
> <CodeMirror
>   value="console.log('hello world!');"
>   height="200px"
>   theme="dark"
>   onStatistics={(data) => {
>     console.log(data.selectionAsSingle);
>   }}
>   extensions={[javascript({ jsx: true })]}
>   onChange={onChange}
> />
> ```
> 
> ```js
> <CodeMirror
>   value="console.log('hello world!');"
>   height="200px"
>   theme="dark"
>   ref={($ref) => {
>     if ($ref && $ref.view) {
>       console.log("$ref::", $ref.view.state.selection.main);
>     }
>   }}
>   onStatistics={(data) => {
>     console.log(data.selectionAsSingle);
>   }}
>   extensions={[javascript({ jsx: true })]}
>   onChange={onChange}
> />
> ```
> 
> @arbob Exampel https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-wixg3f?fontsize=14&hidenavigation=1&theme=dark
