### ISSUE TITLE
Can't Override Mod+Enter keymap

### ISSUE THREAD

**Issue by abhirampai** [uiwjs/react-codemirror#356]
Tried out overriding mod+enter but it didn't work as expected.

```
keymap.of([
      {
        key: "Mod-Enter",
        preventDefault: true,
        run: () => {
          alert("running");
          return true;
        }
      }
    ])
```

I tried out Shift-Enter and that worked perfectly.

```
keymap.of([
      {
        key: "Shift-Enter",
        preventDefault: true,
        run: () => {
          alert("running");
          return true;
        }
      }
    ])
```

<img width="1438" alt="Screenshot 2022-07-11 at 7 44 45 PM" src="https://user-images.githubusercontent.com/36255896/178284962-d3cd9de5-8395-4eaf-a656-ce6e978ad869.png">

Attaching code sandbox link in which I tried out the same https://codesandbox.io/s/zen-solomon-kg3y1p?file=/src/Components/CodeEditor/index.jsx:519-716

**Comment by jaywcjlove** [comment]
@abhirampai https://codesandbox.io/embed/blazing-leaf-81cic6?fontsize=14&hidenavigation=1&theme=dark


The default keymap. Includes all bindings from
[`standardKeymap`](https://codemirror.net/6/docs/ref/#commands.standardKeymap) plus the following:

- Alt-ArrowLeft (Ctrl-ArrowLeft on macOS): [`cursorSyntaxLeft`](https://codemirror.net/6/docs/ref/#commands.cursorSyntaxLeft) ([`selectSyntaxLeft`](https://codemirror.net/6/docs/ref/#commands.selectSyntaxLeft) with Shift)
- Alt-ArrowRight (Ctrl-ArrowRight on macOS): [`cursorSyntaxRight`](https://codemirror.net/6/docs/ref/#commands.cursorSyntaxRight) ([`selectSyntaxRight`](https://codemirror.net/6/docs/ref/#commands.selectSyntaxRight) with Shift)
- Alt-ArrowUp: [`moveLineUp`](https://codemirror.net/6/docs/ref/#commands.moveLineUp)
- Alt-ArrowDown: [`moveLineDown`](https://codemirror.net/6/docs/ref/#commands.moveLineDown)
- Shift-Alt-ArrowUp: [`copyLineUp`](https://codemirror.net/6/docs/ref/#commands.copyLineUp)
- Shift-Alt-ArrowDown: [`copyLineDown`](https://codemirror.net/6/docs/ref/#commands.copyLineDown)
- Escape: [`simplifySelection`](https://codemirror.net/6/docs/ref/#commands.simplifySelection)
- Ctrl-Enter (Comd-Enter on macOS): [`insertBlankLine`](https://codemirror.net/6/docs/ref/#commands.insertBlankLine)
- Alt-l (Ctrl-l on macOS): [`selectLine`](https://codemirror.net/6/docs/ref/#commands.selectLine)
- Ctrl-i (Cmd-i on macOS): [`selectParentSyntax`](https://codemirror.net/6/docs/ref/#commands.selectParentSyntax)
- Ctrl-[ (Cmd-[ on macOS): [`indentLess`](https://codemirror.net/6/docs/ref/#commands.indentLess)
- Ctrl-] (Cmd-] on macOS): [`indentMore`](https://codemirror.net/6/docs/ref/#commands.indentMore)
- Ctrl-Alt-\\ (Cmd-Alt-\\ on macOS): [`indentSelection`](https://codemirror.net/6/docs/ref/#commands.indentSelection)
- Shift-Ctrl-k (Shift-Cmd-k on macOS): [`deleteLine`](https://codemirror.net/6/docs/ref/#commands.deleteLine)
- Shift-Ctrl-\\ (Shift-Cmd-\\ on macOS): [`cursorMatchingBracket`](https://codemirror.net/6/docs/ref/#commands.cursorMatchingBracket)
- Ctrl-/ (Cmd-/ on macOS): [`toggleComment`](https://codemirror.net/6/docs/ref/#commands.toggleComment).
- Shift-Alt-a: [`toggleBlockComment`](https://codemirror.net/6/docs/ref/#commands.toggleBlockComment).

**Comment by abhirampai** [comment]
Oh ok got it. So setting the default keymap to false will only work in this case? Is there any other way in which I can override only the cmd-enter or ctrl-enter keymap while keeping the other keymaps intact?

**Comment by jaywcjlove** [comment]
@abhirampai There is no good way to cover it.

**Comment by abhirampai** [comment]
Ok, Thank you for the response.

**Comment by steppy452** [comment]
@abhirampai I ran into this problem as well and found this thread. Disabling defaultKeymap worked for me but I also only wanted to override cmd-enter. This seems to do what I think we both want so hopefully it helps you too:

```
import { defaultKeymap } from '@codemirror/commands';

...

keymap.of([
  {
    key: 'Cmd-Enter',
    run() {
      if (!loading) onRun();
      return true;
    },
  },
  ...defaultKeymap, // add in all of the default keymappings from codemirror
]);
```

**Comment by abhirampai** [comment]
Thanks, @steppy452 , This works.

> @abhirampai I ran into this problem as well and found this thread. Disabling defaultKeymap worked for me but I also only wanted to override cmd-enter. This seems to do what I think we both want so hopefully it helps you too:
> 
> ```
> import { defaultKeymap } from '@codemirror/commands';
> 
> ...
> 
> keymap.of([
>   {
>     key: 'Cmd-Enter',
>     run() {
>       if (!loading) onRun();
>       return true;
>     },
>   },
>   ...defaultKeymap, // add in all of the default keymappings from codemirror
> ]);
> ```
