### ISSUE TITLE
Adding syntax highlight based on language name

### ISSUE THREAD

**Issue by alok8bb** [uiwjs/react-codemirror#360]
Hello, I have a react-codemirror editor with some text as value. I want to add syntax highlighting to it based on a variable that is just the type of programming language of text. Its a read-only and not editable codemirror editor. 

How can I achieve this? 

I couldn't find any working example of what I want to do and also no forum for react-codemirror so making an issue. 
Thanks.

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/e09dc4dc0ca2f4ba8c5d4f2393249600d0d6ecfb/www/src/langs.ts#L42-L87

https://github.com/uiwjs/react-codemirror/blob/e09dc4dc0ca2f4ba8c5d4f2393249600d0d6ecfb/www/src/pages/home/Example.tsx#L75-L97

I'm not sure if that's what you want.
@alok8bb

**Comment by alok8bb** [comment]
> I may not have understood what you meant.

I'm writing a paste-bin. In the read only editor codemirror component, I'm assigning the value which can be of different programming languages, the language is also given. [This]( https://github.com/uiwjs/react-codemirror#support-language) but for multiple languages. I'm getting the language and text as props from parent component. 
So if once I get text that is golang's code then I would want go's syntax highlight in editor.

Sorry for poor explanation, hope it makes sense.

**Comment by jaywcjlove** [comment]
@alok8bb 

```jsx
import React from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { javascript } from '@codemirror/lang-javascript';

export const getLangs = (name) => {
  const langs = {
    javascript,
    jsx: () => javascript({ jsx: true }),
    typescript: () => javascript({ typescript: true }),
    tsx: () => javascript({ jsx: true, typescript: true }),
  }
  return langs[name]
}

function App() {
  const extensions = getLangs('javascript')
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={extensions ? [extensions] : []}
    />
  );
}
```

**Comment by alok8bb** [comment]
> @alok8bb
> 
> ```js
> import React from 'react';
> import CodeMirror from '@uiw/react-codemirror';
> import { javascript } from '@codemirror/lang-javascript';
> 
> export const getLangs = (name) => {
>   const langs = {
>     javascript,
>     jsx: () => javascript({ jsx: true }),
>     typescript: () => javascript({ typescript: true }),
>     tsx: () => javascript({ jsx: true, typescript: true }),
>   }
>   return langs[name]
> }
> 
> function App() {
>   const extensions = getLangs('javascript')
>   return (
>     <CodeMirror
>       value="console.log('hello world!');"
>       height="200px"
>       extensions={extensions ? [extensions] : []}
>     />
>   );
> }
> ```

I'll still have to define all the possible languages?

**Comment by jaywcjlove** [comment]
@alok8bb Oh I should develop a loader language extension

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/html-matchclosingtags-configure-language-when-loading-with-language-data-pack/4581/4

https://discuss.codemirror.net/t/highlighting-nested-markdown-and-within-javascript-template-strings/3342

**Comment by jaywcjlove** [comment]
https://codemirror.net/examples/config/#automatic-language-detection

**Comment by alok8bb** [comment]
Thanks @jaywcjlove  for your quick response and creating the extension. 

I am using typescript, and setting  `extension = {[loadLanguage("shell")]` but there's this error: 
```shell
(alias) loadLanguage(name: "html" | "q" | "ruby" | "apl" | "asciiArmor" | "asterisk" | "c" | "csharp" | "scala" | "kotlin" | "shader" | "nesC" | "objectiveC" | "objectiveCpp" | "squirrel" | "ceylon" | ... 101 more ... | "r"): StreamLanguage<...> | ... 1 more ... | null
import loadLanguage
Type 'StreamLanguage<unknown> | LanguageSupport | null' is not assignable to type 'Extension'.
  Type 'null' is not assignable to type 'Extension'.
```

If I add a check 
`extension={[loadLanguage("tsx")  == null ? langs.shell() : loadLanguage("tsx")}` but the error remains the same because still the there's one `null` return. 
How should I implement this?

**Comment by jaywcjlove** [comment]
@alok8bb 

https://github.com/uiwjs/react-codemirror/blob/36d0ab9155e084fa0b83c43427a7f00768eaec3b/www/src/pages/extensions/langs/index.tsx#L45

```js
[loadLanguage(language)!].filter(Boolean)
```
