### ISSUE TITLE
How to dynamically set height？

### ISSUE THREAD

**Issue by YuAoi** [uiwjs/react-codemirror#362]
How to dynamically set height？

**Comment by jaywcjlove** [comment]
@YuAoi Not sure if it's what you want: https://codesandbox.io/embed/react-codemirror-example-codemirror-6-forked-gkwcbj?fontsize=14&hidenavigation=1&theme=dark

```jsx
<CodeMirror
  value="console.log('hello world!');"
+  height="100%"
  style={{
+    height: '100%'
  }}
/>
```

**Comment by YuAoi** [comment]
@jaywcjlove 老哥，简直太棒了。这个用法有点奇怪，但是很有效。
