### ISSUE TITLE
Unexpected Behaviour On Snippets, When Moving Cursor Using <Tab>

### ISSUE THREAD

**Issue by JustIdentity** [uiwjs/react-codemirror#363]
When we're using snippets autocompletion with multiple placeholder, <Tab> and <Shift-Tab> key are used to move between placeholder as expected on codemirror demo website
![codemirror](https://user-images.githubusercontent.com/66266045/181772701-83720ff9-94f2-4878-8107-52d7b482f5b3.gif)
[Link](https://codemirror.net/)

While in @uiw/react-codemirror, unexpected behaviour happen. Instead move to next placeholder, <Tab> key will add '\t' to start of the line.
![@uiw/reac-codemirror](https://user-images.githubusercontent.com/66266045/181772686-58f913ba-0f80-4d77-b1b3-1fbaff9ece84.gif)
[Link](https://uiwjs.github.io/react-codemirror/)

Extension used in codemirror website ([src](https://github.com/codemirror/website/blob/master/site/demo.js)):
```javascript
  extensions: [
    basicSetup,
    javascript(),
    javascriptLanguage.data.of({autocomplete: jsCompletion})
  ]
```

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-363-fvq0tl?fontsize=14&hidenavigation=1&theme=dark

@JustIdentity I did not reproduce your problem.

I'm not sure if I understand wrong.

**Comment by JustIdentity** [comment]
I guess you were right, the real reason why I am submit this issue is because I want to make custom snippet like [this](https://codesandbox.io/s/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-363-forked-k30wyk?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js). And working as expected. (I am still not sure why on [this](https://uiwjs.github.io/react-codemirror/) website don't work as expected on my computer)

In the meantime, if you have spare time. Can you check where I did wrong?
![image](https://user-images.githubusercontent.com/66266045/181782009-7bdae865-6a06-4e1f-aa82-81d9651bc29c.png)
![image](https://user-images.githubusercontent.com/66266045/181782053-e0cada09-be3f-48f8-9499-7db8a62dece4.png)

Result:
![A](https://user-images.githubusercontent.com/66266045/181782379-103a4c1e-3d67-4ce0-8575-747588453d7e.gif)

**Comment by jaywcjlove** [comment]
I preview your example, is the expected behavior.

Is it a browser compatibility issue?

@JustIdentity

**Comment by JustIdentity** [comment]
Found out the problem, the reason why it's resetting is because I use setter. So the whole element re-rendered. And probably that's the reason why the website didn't work.

**Comment by jaywcjlove** [comment]
```jsx
import React from "react";
import CodeMirror from "@uiw/react-codemirror";
import { snippetCompletion } from "@codemirror/autocomplete";
import { markdown, markdownLanguage } from "@codemirror/lang-markdown";

export default function App() {
  return (
    <div>
      <CodeMirror
        value="console.log('hello world!');"
        height="200px"
        extensions={[
          markdown(),
          markdownLanguage.data.of({
            autocomplete: [
              snippetCompletion("hello(${1}, ${2}) ${}", { label: "hello" })
            ]
          })
        ]}
        onChange={(value, viewUpdate) => {
          console.log("value:", value);
        }}
      />
    </div>
  );
}

```

**Comment by JustIdentity** [comment]
I think I will refactor CodeMirror Element, so it wont re-render every time the value change. Btw, thanks for the hardwork
