### ISSUE TITLE
Regular + peer dependencies?

### ISSUE THREAD

**Issue by rexxars** [uiwjs/react-codemirror#367]
Hi! Thanks for this great project!

I was wondering about the dependency setup of the main module. It has the following:
```json
"peerDependencies": {
  "@babel/runtime": ">=7.11.0",
  "@codemirror/theme-one-dark": ">=6.0.0",
  "@codemirror/view": ">=6.0.0",
  "codemirror": ">=6.0.0",
  "react": ">=16.8.0",
  "react-dom": ">=16.8.0"
},
"dependencies": {
  "@babel/runtime": "^7.18.6",
  "@codemirror/theme-one-dark": "^6.0.0",
  "@uiw/codemirror-extensions-basic-setup": "4.11.4",
  "codemirror": "^6.0.0"
},
```

I am a little confused as to why `@babel/runtime`, `@codemirror/theme-one-dark` and `codemirror` are present in both the peer _and_ regular dependencies?

I would think that having them as regular dependencies would be enough?

**Comment by jaywcjlove** [comment]
@rexxars 

`@codemirror/theme-one-dark` depends on

```js
"@lezer/highlight": "^1.0.0",
"@codemirror/language": "^6.0.0",
"@codemirror/state": "^6.0.0",
"@codemirror/view": "^6.0.0"
```

will cause [#216](https://github.com/uiwjs/react-codemirror/issues/216) problems

**Comment by rexxars** [comment]
Not sure I understand... 

Lets take the `@codemirror/theme-one-dark` as an example:
- The _peer_ dependency range says "any version at or above 6.0.0"
- The _dependency_ range says "any version on the 6.0.0 range`

If some other part of your app depends on `@codemirror/theme-dark-one` at version `7.0.0`, the _peer_ says it is compatible, but the _dependency_ is _not_ compatible, so it will install both 7 and 6. This may be the expected and wanted behavior - but it would be the same even if removing `@codemirror/theme-one-dark` from peer dependencies, I think?

Maybe I'm missing something obvious here. Feel free to close and ignore if you don't have time for this :)

**Comment by jaywcjlove** [comment]
@rexxars 

In `codemirror`, `@codemirror/view` and `@codemirror/state` must depend on the same.

`@codemirror/theme-one-dark` depends on these two libraries, so it needs to be marked.

**Comment by rexxars** [comment]
I see, thanks for the explainer.
