### ISSUE TITLE
Add custom lint error marker on react-codemirror

### ISSUE THREAD

**Issue by venkat-subramani** [uiwjs/react-codemirror#386]
I want to display lint errors which I receive from external API. 
Error information I receive from the API is 
    1. Line number
    2. Error description

I would like to add a custom marker with tooltip in the codemirror gutter area. I've found this answer on stackoverflow https://stackoverflow.com/a/72219083 but unable to implement on react-codemirror.

**Comment by jaywcjlove** [comment]
Example: Linter: https://codemirror.net/examples/lint/

**Comment by venkat-subramani** [comment]
@jaywcjlove Thanks for your response. I'm able to use linter on code area now.
Is it possible to display error marker on line numbers in gutter area ?

**Comment by jaywcjlove** [comment]
@venkat-subramani 
https://codemirror.net/examples/gutter/

**Comment by venkat-subramani** [comment]
Adding lintGutter() in the extensions list added the error marking for my lints.

**Comment by AndrewThian** [comment]
@venkat-subramani I'm sorry to reopen this thread but could you help with an example of how you used `js-yaml` with react-codemirror for the lint source? I'm having trouble according to the [link](https://discuss.codemirror.net/t/yaml-linter-for-uiw-react-codemirror-or-codemirror-v6/4976) provided
