### ISSUE TITLE
Manually set caret (cursor) position?

### ISSUE THREAD

**Issue by svobodazdenek** [uiwjs/react-codemirror#388]
Hello, 
I'd like to ask if it is possible to manually set the caret (cursor) position in text? 
I've been playing around with it the whole day unable to get it working and I'm also not so skilled. 

The reason why I want to manually change the position is - I want to insert text somewhere inside the editor content and after the text is inserted - move the caret at the end of the insertion. Maybe there is another way, but I haven't found it.

If someone knows how to do it then please show me a working example. Thanks a lot

**Comment by jaywcjlove** [comment]
@svobodazdenek example here:  https://github.com/uiwjs/react-markdown-editor/blob/c065faf7c600473748450043c946ba6649e8dbb4/src/commands/bold.tsx#L16-L27

**Comment by jaywcjlove** [comment]
```js
view.dispatch(
  view.state.changeByRange((range) => ({
    changes: [
      { from: range.from, insert: '**' },
      { from: range.to, insert: '**' },
    ],
    range: EditorSelection.range(range.from + 2, range.to + 2),
  })),
);
```

**Comment by svobodazdenek** [comment]
You are my hero :D , thank you so much !!!
