### ISSUE TITLE
Is there a method to use a json-schema file to handle linting/auto-completion?

### ISSUE THREAD

**Issue by musab** [uiwjs/react-codemirror#389]
After searching, I don't see any mention of using a json-schema file. 

For example, can we load a json-schema (one of the files from https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json) to handle linting and auto-completion? (Any examples of this anywhere?)

**Comment by musab** [comment]
@jaywcjlove An example is the GitHub Actions editor which is using https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json for linting and autosuggestions.

<img width="1078" alt="Screen Shot 2022-10-18 at 11 59 55 AM" src="https://user-images.githubusercontent.com/34455928/196482816-9fff0feb-426f-42f3-9635-78501c089572.png">

--- 

In editors like VS Code these files offer auto-completion and validation to ensure your JSON document is correct. I especially like the fact that the schema is open source. 

In Monaco Editor you would pass the following to enable the json schema (more info: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.json.DiagnosticsOptions.html#schemas)

```js
 languages.yaml.yamlDefaults.setDiagnosticsOptions({
      validate: true,
      enableSchemaRequest: true,
      hover: true,
      completion: true,
      schemas: [
        {
          uri: 'https://json.schemastore.org/circleciconfig.json',
          fileMatch: ['*'],
        },
      ],
    });
```

I may be off base here, and this isn't something CodeMirror natively supports?

**Comment by jaywcjlove** [comment]
@musab You may need to find the answer [here](https://discuss.codemirror.net/).

**Comment by musab** [comment]
Thank you!
