### ISSUE TITLE
How to get the content 

### ISSUE THREAD

**Issue by kaushikc44** [uiwjs/react-codemirror#391]
Hi I am interested to know how to get the contents of codemirror , that is written in it.

**Comment by jaywcjlove** [comment]
@kaushikc44  use ref

https://github.com/uiwjs/react-codemirror/blob/b2341d3f8fb94345cbb759382870d81c61606812/core/src/index.tsx#L141-L146

**Comment by kaushikc44** [comment]
I am kind of new to react so I don't exactly know ref but `const [compo, setCompo] = useState(<CodeMirror  options={{mode:'javascript', lineNumbers:true}} value="console.log('hello world')"
height="80vh"
width="170vh" 
theme={themefunc()}
onChange={(editor,data,value) => {console.log(value)}} />);
let arrary = [{1:{key1:iconstate,key2:compo}}]`
This is what I am trying to implement . I want to get the content. upon changes.

**Comment by kaushikc44** [comment]
Never mind got it , thanks alot. Can you also have a example folder so we can showcase  our projects built using codemirror. Thanks
