### ISSUE TITLE
如何格式化？

### ISSUE THREAD

**Issue by kingcwt** [uiwjs/react-codemirror#394]
如果value是字符串 如何格式化代码 而不是一行展示

**Comment by jaywcjlove** [comment]
@kingcwt 编辑器并不代格式化功能，这需要你自己编写，类似 https://github.com/kufii/sql-formatter-plus

也许你可以在官方论坛寻找答案 https://discuss.codemirror.net

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/t/how-to-set-json-formatter-of-codemorrir-next/4090/2

**Comment by yunnan-tibet** [comment]
> 我找到了一种格式化的方式，其实我就是想简单的做个自动缩进，但是不知道如何获取到这个editor实例 https://codemirror.net/2/demo/formatting.html ![image](https://private-user-images.githubusercontent.com/2985895/288708494-d15bf3bd-2b56-4a79-94cf-d9347930ddec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzgyMjYsIm5iZiI6MTcxOTQ3NzkyNiwicGF0aCI6Ii8yOTg1ODk1LzI4ODcwODQ5NC1kMTViZjNiZC0yYjU2LTRhNzktOTRjZi1kOTM0NzkzMGRkZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDg0NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRlY2I0NjJkYjc1MmUxY2M1ZmM4Y2YxNWE5MDhkMDkyZDc2ZjcwMGY3MTY3YjFiY2MxODU2MGQ2MTc5ODUxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8sl4xo9RtGK2DyYPbdLGFurSA377U2sFUkqv9Yb9a_4)

JSON.stringify(value, null, 2)即可
