### ISSUE TITLE
How to overwrite search , check box , next and previous components into custom components

### ISSUE THREAD

**Issue by dev-mohanraj** [uiwjs/react-codemirror#396]
Can I able to override the existing styles of the search and other components

**Comment by jaywcjlove** [comment]
@dev-mohanraj Styles can be overridden.

https://github.com/uiwjs/react-codemirror/blob/b2341d3f8fb94345cbb759382870d81c61606812/themes/theme/src/index.tsx#L43-L93

**Comment by chiptus** [comment]
@jaywcjlove you're answer doesn't have search theme

**Comment by dev-mohanraj** [comment]
Thanks @jaywcjlove

**Comment by dev-mohanraj** [comment]
Can I replace the default search to consume a custom component @jaywcjlove
