### ISSUE TITLE
如何使用 codemirror 的标记高亮功能

### ISSUE THREAD

**Issue by h7ml** [uiwjs/react-codemirror#397]
![image](https://user-images.githubusercontent.com/55233292/198495660-daeb041c-c1c2-437a-94b0-3553aecd4524.png)

**Comment by jaywcjlove** [comment]
@h7ml 没有明白你的意思？你要干什么？ 用的是老的版本？

**Comment by h7ml** [comment]
> @h7ml 没有明白你的意思？你要干什么？ 用的是老的版本？
```codemirror``` 相关 ``dependencies``
```
    "@codemirror/lang-css": "^6.0.0",
    "@codemirror/lang-javascript": "6.0.2",
    "@codemirror/theme-one-dark": "^6.0.0",
    "@uiw/codemirror-extensions-color": "^4.11.4",
    "@uiw/codemirror-themes": "4.11.6",
    "@uiw/react-codemirror": "^4.11.4",
```

我需要使用 [codemirror markText ](https://codemirror.net/5/doc/manual.html#markText) 功能

**Comment by jaywcjlove** [comment]
@h7ml  我看你截图使用的是 v3，你发的依赖是 v4，你发的 codemirror markText  又是 CM v5 老的文档

`@uiw/react-codemirror` v3 对应的 `CM v5`  
`@uiw/react-codemirror` v4 对应的 `CM v6`  

`CM v5` 与 `CM v6` 不兼容

**Comment by jaywcjlove** [comment]
@h7ml v3 文档 https://raw.githack.com/uiwjs/react-codemirror/doc3/index.html

**Comment by h7ml** [comment]
> @h7ml 我看你截图使用的是 v3，你发的依赖是 v4，你发的 codemirror markText 又是 CM v5 老的文档
> 
> `@uiw/react-codemirror` v3 对应的 `CM v5` `@uiw/react-codemirror` v4 对应的 `CM v6`
> 
> `CM v5` 与 `CM v6` 不兼容

![image](https://user-images.githubusercontent.com/55233292/198521245-e276d690-66c9-4f2f-baed-f12910004fb2.png)
好的。查看了依赖。应该查看cm v6的文档。

**Comment by h7ml** [comment]
https://codemirror.net/examples/decoration/
