### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by thiagoarantes** [uiwjs/react-codemirror#403]
Is linting available in this wrapper? Can't seem to be able to add it in basicSetup or anywhere else.
I am testing it with javascript language, that is supported by default in codemirror.net
https://codemirror.net/5/demo/lint.html

**Comment by jaywcjlove** [comment]
https://codemirror.net/docs/ref/#lint
codemirror v6 Example: https://codemirror.net/examples/lint/

If you use codemirror v5 use @uiw/react-codemirror `v3`.

If you use codemirror v6 use @uiw/react-codemirror `v4`.

@thiagoarantes

**Comment by thiagoarantes** [comment]
From the example: https://codemirror.net/examples/lint/ 

> The library does not come with a collection of lint sources. Some language packages (such as [@codemirror/lang-javascript](https://github.com/codemirror/lang-javascript/#user-content-eslint)) **may include integration with lint libraries**, but usually setting up a source is something you have to do yourself.

I understand by this that javascript package should come with some linting features. I don't see any being applied, though. Thoughts?

Tks!

**Comment by jaywcjlove** [comment]
I don't have a very good idea yet because I don't have a similar application in my project.
@thiagoarantes

**Comment by bryandowning** [comment]
@thiagoarantes From: https://github.com/codemirror/lang-javascript/#user-content-eslint

<dt id="user-content-eslint">
  <code><strong><a href="#user-content-eslint">esLint</a></strong>(<a id="user-content-eslint^eslint" href="#user-content-eslint^eslint">eslint</a>: any, <a id="user-content-eslint^config" href="#user-content-eslint^config">config</a>&#8288;?: any) → fn(<a id="user-content-eslint^returns^view" href="#user-content-eslint^returns^view">view</a>: <a href="https://codemirror.net/docs/ref#view.EditorView">EditorView</a>) → <a href="https://codemirror.net/docs/ref#lint.Diagnostic">Diagnostic</a>[]</code></dt>

<dl>
<dd><p>Connects an <a href="https://eslint.org/">ESLint</a> linter to CodeMirror's
<a href="https://codemirror.net/docs/ref/#lint">lint</a> integration. <code>eslint</code> should be an instance of the
<a href="https://eslint.org/docs/developer-guide/nodejs-api#linter"><code>Linter</code></a>
class, and <code>config</code> an optional ESLint configuration. The return
value of this function can be passed to <a href="https://codemirror.net/docs/ref/#lint.linter"><code>linter</code></a>
to create a JavaScript linting extension.</p>
<p>Note that ESLint targets node, and is tricky to run in the
browser. The
<a href="https://github.com/UziTech/eslint-linter-browserify">eslint-linter-browserify</a>
package may help with that (see
<a href="https://github.com/UziTech/eslint-linter-browserify/blob/master/example/script.js">example</a>).</p>
</dd>
</dl>


This means you need to:
`npm install @codemirror/lint`

...then something like this

```
import {linter} from '@codemirror/lint'
import {javascript, esLint} from '@codemirror/lang-javascript'

const esLinter = linter(esLint(/* esLint Linter instance, esLint config */))

/*...*/

<CodeMirror extensions={[javascript(), esLinter]} />
```

**Comment by thiagoarantes** [comment]
Thanks!
