### ISSUE TITLE
Bug: Highlighting selection on active line doesn't work

### ISSUE THREAD

**Issue by notmedia** [uiwjs/react-codemirror#406]
Hi! The problem here is that when you setup selection color it doesn't highlight selection on active line. For default theme it works.

In this example I selected `'#4D4D4C',` string, you can see that match selection worked.

<img width="713" alt="Screenshot 2022-11-14 at 00 56 21" src="https://user-images.githubusercontent.com/12993018/201546610-ceb94b69-2c0e-4aed-9f8f-2ba37c16a1e0.png">

**Comment by jaywcjlove** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1680273/202359461-8f419c83-8338-4b50-bfb7-1cb794f82cc1.png">

https://github.com/uiwjs/react-codemirror/blob/09521ddade2b3ebc86811f6e006dece0182c79aa/www/src/pages/theme/editor/index.tsx#L75-L86

@notmedia I found no errors.

**Comment by notmedia** [comment]
@jaywcjlove Hey! Try to select text on **active line**, you may see that selection is invisible there

**Comment by jaywcjlove** [comment]
I fixed it. @notmedia Upgrade `v4.14.2`

**Comment by notmedia** [comment]
@jaywcjlove Hi! Thank you, but I found another bug here.
If you define **selection** color and **lineHighlight** color then selection is also invisible on active line.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/12993018/202531429-27d0ba18-fcb9-4378-9707-2e5fed609a51.png">

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/codemirror-uiwjs-react-codemirror-issues-406-s6m8mc?fontsize=14&hidenavigation=1&theme=dark

I created a new `codemirror` example to test it. Looks fine.

** selection** word, **lineHighlight** hides

Maybe I didn't understand your question.

@notmedia

**Comment by notmedia** [comment]
@jaywcjlove I took a video 

Uploading Screen Recording 2022-11-18 at 16.40.00.mov…

**Comment by notmedia** [comment]
@jaywcjlove But on official webpage it works(

Uploading Screen Recording 2022-11-18 at 17.30.16.mov…

**Comment by jaywcjlove** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1680273/202728586-147509ab-6f67-4fce-a70e-0067c0473b8b.png">

@notmedia using a transparent color

**Comment by notmedia** [comment]
@jaywcjlove Yeah, it works! Thank you :)

**Comment by elitenas** [comment]
I think the bug here is that if the text is selected... the activeLine class should be removed. This bug was introduced after 4.11.6

**Comment by notmedia** [comment]
No, because you need to see active line in selection if you select 2+ lines

**Comment by elitenas** [comment]
if we set activeLine to transparent to see the highlight or selection then we dont see which line is active ever
