### ISSUE TITLE
VS Code Dark Theme?

### ISSUE THREAD

**Issue by karlhorky** [uiwjs/react-codemirror#409]
Would it be possible to get a theme similar to VS Code Dark?

It could be based on this one here: https://github.com/upleveled/theme-vs-code-dark-plus/blob/main/src/vs-code-dark-plus.ts

There are some for other editors as well:

- https://github.com/PrismJS/prism-themes/blob/master/themes/prism-vsc-dark-plus.css

**Comment by jaywcjlove** [comment]
@karlhorky 

<a href="https://uiwjs.github.io/react-codemirror/#/theme/data/vscode/dark">
  <img width="436" alt="codemirror-theme-vscode dark" src="https://user-images.githubusercontent.com/1680273/202343079-7eca1c90-da69-4ef2-a18c-4c9f5ea4e396.png">
</a>

## Install

```bash
npm install @uiw/codemirror-theme-vscode --save
```

## Usage

```jsx
import CodeMirror from '@uiw/react-codemirror';
import { vscodeDark } from '@uiw/codemirror-theme-vscode';
import { javascript } from '@codemirror/lang-javascript';

function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      theme={vscodeDark}
      extensions={[javascript({ jsx: true })]}
      onChange={(value, viewUpdate) => {
        console.log('value:', value);
      }}
    />
  );
}
export default App;
```

```js
import { EditorView } from '@codemirror/view';
import { EditorState } from '@codemirror/state';
import { javascript } from '@codemirror/lang-javascript';
import { vscodeDark } from '@uiw/codemirror-theme-vscode';

const state = EditorState.create({
  doc: 'my source code',
  extensions: [vscodeDark, javascript({ jsx: true })],
});

const view = new EditorView({
  parent: document.querySelector('#editor'),
  state,
});
```

**Comment by karlhorky** [comment]
Nice, thanks!

However, it seems that the background color is not currently `#1e1e1e`, which is the style that VS Code has (also in my theme [here](https://github.com/upleveled/theme-vs-code-dark-plus/blob/9e16ebf6b4dae917ee0bbb2ff1e3db8c35370ae2/src/vs-code-dark-plus.ts#L9)):

![Screenshot 2022-11-17 at 12 02 40](https://user-images.githubusercontent.com/1935696/202431443-3a1e9a12-9a7b-462f-bfe8-0918149ab44d.png)

**Comment by jaywcjlove** [comment]
@karlhorky Upgrade `v4.14.1`

**Comment by karlhorky** [comment]
Looking better already!

A few more things (screenshots for reference below):

1. Colors - PR fixing this here: #412
   - The foreground color is dark blue/turquoise in the `@uiw/codemirror-theme-vscode` theme but light blue in VS Code
   - The function name color is dark blue/turquoise in the `@uiw/codemirror-theme-vscode` theme but light yellow in VS Code
2. Would you support a `font-family` in your themes? In the original theme, the font-family that looked closest was a `font-family` of `'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", "Courier New", monospace'` for the class `'&.cm-editor .cm-scroller'`

`@uiw/codemirror-theme-vscode`

![Screenshot 2022-11-17 at 15 37 28](https://user-images.githubusercontent.com/1935696/202475451-c98e3423-d3a7-4e0b-98ec-de2c274e4e39.png)

[theme-vs-code-dark-plus](https://github.com/upleveled/theme-vs-code-dark-plus)

![Screenshot 2022-11-17 at 15 37 53](https://user-images.githubusercontent.com/1935696/202475431-03aa1dd0-44d1-4aae-bbdb-3808e74c4a10.png)

**Comment by jaywcjlove** [comment]
The font depends on what font is used in the outer layer.

The fixed font will have a different style from the entire page, and it will be very inconvenient to modify.

There is no fixed font, so setting the font is very flexible.

@karlhorky

**Comment by karlhorky** [comment]
Ok, trying to understand: So does that mean that there will be no support for setting `font-family` in a `@uiw/react-codemirror` theme?

**Comment by jaywcjlove** [comment]
```ts
import { tags as t } from '@lezer/highlight';
import { createTheme, CreateThemeOptions  } from '@uiw/codemirror-themes';

initTheme({ settings: { fontFamily: 'Menlo, Monaco, Consolas, "Andale Mono", "Ubuntu Mono", "Courier New", monospace' }})

export function initTheme(options: CreateThemeOptions) {
  const { theme = 'dark', settings = {}, styles = [] } = options || {}
  return createTheme({
    theme: theme,
    settings: {
      background: '#1e1e1e',
      foreground: '#9cdcfe',
      caret: '#c6c6c6',
      selection: '#6199ff2f',
      selectionMatch: '#72a1ff59',
      lineHighlight: '#ffffff0f',
      gutterBackground: '#1e1e1e',
      gutterForeground: '#838383',
      gutterActiveForeground: '#fff',
      ...settings
    },
    styles: [
      { tag: t.keyword, color: '#569cd6' },
      ...styles
    ],
  });
}


export const vscodeDark = initTheme;
```

@karlhorky This design api should be able to meet the needs of setting fonts, and also can reset fonts

**Comment by karlhorky** [comment]
Nice, thanks for 6fa5ad5! 

So my last question would be: do you support adding this to the theme itself? #413

**Comment by jaywcjlove** [comment]
@karlhorky ultimate solution


```jsx
import { vscodeDark, vscodeDarkInit } from '@uiw/codemirror-theme-vscode';

<CodeMirror theme={vscodeDark} />

<CodeMirror
  theme={vscodeDarkInit({
    fontFamily: 'monospace',
  })}
/>
```

**Comment by karlhorky** [comment]
Cool, that's nice!

**Comment by karlhorky** [comment]
Screenshot of final theme after changes:

<img width="368" alt="Screenshot 2022-11-17 at 17 18 56" src="https://user-images.githubusercontent.com/1935696/202500700-11643593-5385-4d5b-9f41-1414dc4ddba5.png">

PR open here: https://github.com/uiwjs/react-codemirror/pull/414

**Comment by jaywcjlove** [comment]
@karlhorky Thank you very much 🙏, hard work.

**Comment by karlhorky** [comment]
Thank you too! 🙌 Super fast iteration and pairing 👍

**Comment by karlhorky** [comment]
@jaywcjlove it seems like the Themes docs site is currently broken? (or maybe the theme itself somehow?)

- The link on the main page of [the Themes docs home page](https://uiwjs.github.io/react-codemirror/#/theme/home) is pointing at https://uiwjs.github.io/react-codemirror/#/theme/data/vscode/dark, which is currently 404 (see the destination at the bottom left in the screenshot below)
  <img width="624" alt="Screenshot 2023-06-03 at 23 10 10" src="https://github.com/uiwjs/react-codemirror/assets/1935696/07efd695-536b-4e18-960d-d69e49da5900">
  <img width="616" alt="Screenshot 2023-06-03 at 23 14 16" src="https://github.com/uiwjs/react-codemirror/assets/1935696/3cb7ea9d-924e-4b4f-b4f6-6622aeba81ac">
- The "VS Code" link in the sidebar of all Themes docs pages links to https://uiwjs.github.io/react-codemirror/#/theme/data/vscode, which is not a dark theme and is not the theme described in the issue above
  <img width="755" alt="Screenshot 2023-06-03 at 23 14 22" src="https://github.com/uiwjs/react-codemirror/assets/1935696/510979e4-c142-41a9-bb11-16dd101c5d89">

**Comment by jaywcjlove** [comment]
@karlhorky The bug has been resolved. Thx!

**Comment by karlhorky** [comment]
@jaywcjlove Great, thanks!
