### ISSUE TITLE
Autocomplete icon border-box -> content-box

### ISSUE THREAD

**Issue by karlhorky** [uiwjs/react-codemirror#411]
First of all, thanks again for `@uiw/react-codemirror`, amazing package! 🙌

The styling of the autocomplete icon relies upon it having `box-sizing: content-box;` instead of `box-sizing: border-box;`

`box-sizing: border-box`, key icon overlapping with text:

<img width="249" alt="Screenshot 2022-11-16 at 22 25 05" src="https://user-images.githubusercontent.com/1935696/202297706-9a7298bd-814f-41bc-9cd6-1971e5d6defb.png">

`box-sizing: content-box`, key icon not overlapping with text:

<img width="249" alt="Screenshot 2022-11-16 at 22 24 51" src="https://user-images.githubusercontent.com/1935696/202297716-4bdffb11-5fb7-479d-adbe-4e5239c2889f.png">

Potentially addressed by https://github.com/codemirror/autocomplete/pull/15

**Comment by karlhorky** [comment]
Change was accepted and merged, maybe will be a part of `@codemirror/autocomplete@6.3.3`: https://github.com/codemirror/autocomplete/pull/15#issuecomment-1318738522

Closing here.

**Comment by jaywcjlove** [comment]
@karlhorky 👍
