### ISSUE TITLE
CodeMirror Highlighing not work

### ISSUE THREAD

**Issue by nuo-promise** [uiwjs/react-codemirror#421]
`
import {
  syntaxHighlighting,
  HighlightStyle,
  defaultHighlightStyle
} from '@codemirror/language';

const myHighlightStyle = HighlightStyle.define([
  { tag: tags.keyword, color: '#FC6' },
  { tag: tags.comment, color: '#16A004', fontStyle: 'italic' },
  { tag: tags.strong, color: '#66D9EF', fontStyle: 'bold' },
  {
    tag: tags.heading1,
    fontSize: '1.6em',
    fontWeight: 'bold'
  },
  {
    tag: tags.heading2,
    fontSize: '1.4em',
    fontWeight: 'bold'
  },
  {
    tag: tags.heading3,
    fontSize: '1.2em',
    fontWeight: 'bold'
  }
]);
extensions={[
              syntaxHighlighting(defaultHighlightStyle),
              syntaxHighlighting(myHighlightStyle),
              transparentTheme,
              scrollBottom,
              javascript({ jsx: true }),
              markdown({
                base: markdownLanguage,
                codeLanguages: languages,
                addKeymap: true
              }),
              EditorView.lineWrapping
            ]}
`

**Comment by nuo-promise** [comment]
@jaywcjlove can you help me?

**Comment by nuo-promise** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/46160170/204101829-04810bbb-022f-489d-9f45-c90d377a7635.png">

**Comment by nuo-promise** [comment]
should next
<img width="668" alt="image" src="https://user-images.githubusercontent.com/46160170/204101895-e09c0827-9619-47e1-ba13-f081039cc216.png">

**Comment by jaywcjlove** [comment]
Please provide an example using https://codesandbox.io/ @nuo-promise

**Comment by nuo-promise** [comment]
> Please provide an example using https://codesandbox.io/ @nuo-promise

https://codesandbox.io/s/smoosh-violet-4gsiy1
Ths!

**Comment by nuo-promise** [comment]
@jaywcjlove

**Comment by jaywcjlove** [comment]
@nuo-promise https://codesandbox.io/embed/sad-mirzakhani-19i64b?fontsize=14&hidenavigation=1&theme=dark

deleted `@codemirror/lang-javascript` ....

**Comment by nuo-promise** [comment]
> @nuo-promise https://codesandbox.io/embed/sad-mirzakhani-19i64b?fontsize=14&hidenavigation=1&theme=dark
> 
> deleted `@codemirror/lang-javascript` ....

Still handling style through createTheme is powerful! Ths
