### ISSUE TITLE
Tab size defaults to 2 spaces in version 4.12.4

### ISSUE THREAD

**Issue by sam-rez** [uiwjs/react-codemirror#423]
My tabs are 2 spaces and I want them to be 4. Nothing in the documentation is working. I am on version 4.12.4

```
<CodeMirror
  value={''}
  height="100vh"
  theme={ sublime }
  extensions={ [python()] }
  onChange={codeChange}
/>
```

**Comment by jaywcjlove** [comment]
@sam-rez 

- https://github.com/uiwjs/react-codemirror/issues/400#issuecomment-1306767630

**Comment by jaywcjlove** [comment]
```diff
<CodeMirror
  value="console.log('hello world!');"
  height="200px"
  basicSetup={{
+    tabSize: 4,
  }}
/>
```

or

```jsx
import { indentUnit } from '@codemirror/language';

<CodeMirror
  value="console.log('hello world!');"
  height="200px"
  theme={okaidia}
  extensions={[
    javascript({ jsx: true }),
    indentUnit.of('    ')
  ]}
/>
```

@sam-rez

**Comment by sam-rez** [comment]
The first option gives me the error
`Type '{ tabSize: number; }' is not assignable to type 'boolean | BasicSetupOptions | undefined'.
  Object literal may only specify known properties, and 'tabSize' does not exist in type 'BasicSetupOptions'.ts(2322)
index.d.ts(31, 5): The expected type comes from property 'basicSetup' which is declared here on type 'IntrinsicAttributes & ReactCodeMirrorProps & RefAttributes<ReactCodeMirrorRef>'`

I think it might be typescript issue.

However, the second option worked for me.

**Comment by jaywcjlove** [comment]
@sam-rez Upgrade `v4.15.1`

**Comment by jaywcjlove** [comment]
@sam-rez v4.13.0+ support

**Comment by jaywcjlove** [comment]
@sam-rez or

```jsx
import { indentUnit } from '@codemirror/language';

<CodeMirror
  value="console.log('hello world!');"
  height="200px"
  theme={okaidia}
  extensions={[
    javascript({ jsx: true }),
    indentUnit.of('    ')
  ]}
/>
```

**Comment by sam-rez** [comment]
Upgrading to v14.15.1 solved my issue
