### ISSUE TITLE
Current highlighted line color

### ISSUE THREAD

**Issue by sam-rez** [uiwjs/react-codemirror#424]
When highlighting lines of text, the current highlighted line color is different than the rest. In the image below, line 1 is different than the rest of the highlighted block.

How can I make the entire highlighted block the same color?

![codemirror-highlight](https://user-images.githubusercontent.com/12194657/205463419-6099c4f4-7d3d-40b2-b32f-e1fada385371.png)

**Comment by jaywcjlove** [comment]
@sam-rez https://discuss.codemirror.net/t/highlight-line-function/4627/7

**Comment by jaywcjlove** [comment]
@sam-rez 



```jsx
import CodeMirror from '@uiw/react-codemirror';
import { zebraStripes } from '@uiw/codemirror-zebra-stripes';

function App() {
  return (
    <CodeMirror
      value=""
      height="200px"
      extensions={[
        zebraStripes({
          lineNumber: [1, [3, 6], 10],
          lightColor: '#aca2ff33',
          darkColor: '#aca2ff40',
        }),
      ]}
    />
  );
}
export default App;
```

<img width="591" alt="image" src="https://user-images.githubusercontent.com/1680273/205497300-175c3ffb-cb67-4c08-bc2e-121be6226c7e.png">


<img width="374" alt="image" src="https://user-images.githubusercontent.com/1680273/205497315-03142df7-9354-4af1-b4c9-101b70d72247.png">

**Comment by sam-rez** [comment]
I fixed it by adding 
`highlightActiveLine: false` 
in `basicSetup`
