### ISSUE TITLE
Wrong tooltip position when using inside portal popover

### ISSUE THREAD

**Issue by nirtamir2** [uiwjs/react-codemirror#426]
Hi
I'm using code sandbox together with radix-ui popover

```tsx
    <Popover
      content={
      <div className="absolute">
        <div className="relative">
        <CodeEditor
          value={value}
          width="500px"
          height="500px"
          onChange={setValue}
        />
        </div>
      </div>
      }
    >
      <div className="h-80"></div>
      <div className="bg-red">Open</div>
    </Popover>
```

It seens that the codemirror autocompletion tooltip is not position well according to codemirror code editor.
![image](https://user-images.githubusercontent.com/16452789/206434734-bdfe247c-cd7b-46c0-878b-e55f2930b705.png)

I think it's because radix-ui render the popover in a portal with fixed position and `trasform:translate`

```
style="position: fixed; left: 0px; top: 0px; transform: translate3d(96px, 348px, 0px); min-width: max-content; z-index: 100; --radix-popper-transform-origin:0% 0px;"
```

![image](https://user-images.githubusercontent.com/16452789/206435865-b3616d58-7dd2-4e9d-92b1-ebcdd9bd69b3.png)

and also codemirror renders the autocompletion in a fixed position that does not consider the initial placement with the position calculation. 

![image](https://user-images.githubusercontent.com/16452789/206435431-de58efa1-1ca3-45e5-9245-aaa016fcafb3.png)

How to align the auto-complete tooltip to the right position?

**Comment by jaywcjlove** [comment]
@nirtamir2 You might be able to provide an example using [codesandbox.io](https://codesandbox.io/embed/react-codemirror-example-codemirror-6-language-rz4rh?fontsize=14&hidenavigation=1&theme=dark) so I can take a look.

**Comment by nirtamir2** [comment]
@jaywcjlove 
Thanks for the fast reply! Here is the codesandbox. Click open and then try to auto-complete 

![image](https://user-images.githubusercontent.com/16452789/206450281-6f7b497c-130d-4e64-875c-bacef24e9822.png)


https://codesandbox.io/s/interesting-danny-xixf6p?file=/pages/index.tsx

**Comment by jaywcjlove** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/1680273/206469244-1e85d2cc-0e20-488b-905f-6ad26106b833.png">

`position: fixed;` This style affects the cm interior positioning calculation.

@nirtamir2

**Comment by nirtamir2** [comment]
@jaywcjlove 
Yes, I believe this is the issue.
What can I do about it? 
How to handle it and make the code-mirror styles more isolated so the radix-UI fixed position won't affect the auto-complete positioning?

**Comment by jaywcjlove** [comment]
@nirtamir2 I don't know of any good workarounds.

**Comment by nirtamir2** [comment]
@jaywcjlove 
Thank you for your help.
I believe this is an issue with codemirror library itself (and not related to it's react wrapper).
I think the best thing, for now, is to close this issue and open it in the relevant codemirror repository.
