### ISSUE TITLE
Access to built-in codemirror functions

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [uiwjs/react-codemirror#427]
Hi there!

I use this library and works perfectly, but I would like to know that can I use built-in codemirror functions? 

For example, I'm looking for how I can use `markText()` method?

**Comment by jaywcjlove** [comment]
@arkadiusz-wieczorek `markText` is codemirror 5 API

This needs to use [@uiw/react-codemirror v3](https://github.com/uiwjs/react-codemirror/tree/v3), get the `cm` object through `ref`.

**Comment by jaywcjlove** [comment]
Upgrade CodeMirror 6 Migration Guide: https://codemirror.net/docs/migration/

**Comment by arkadiusz-wieczorek** [comment]
Ohh, does it mean that there is no posibilty to mark text from programmatically?

**Comment by jaywcjlove** [comment]
You need to use cm 6 new API to do it.

**Comment by arkadiusz-wieczorek** [comment]
Many thanks!
