### ISSUE TITLE
editor上的属性怎么触发

### ISSUE THREAD

**Issue by wangyinwei1** [uiwjs/react-codemirror#43]
![image](https://user-images.githubusercontent.com/15857725/80273175-ab30ae00-8702-11ea-8cd2-119c6dc4c961.png)
这些属性怎么触发

**Comment by jaywcjlove** [comment]
@wangyinwei1 使用 `ref`

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/588b8b9c11afda8ad360b9cc8606b3a16234ee6b/src/index.js#L33-L38


通过 ref 能获取到 `codemirror` 和 `editor` 对象

**Comment by huiminlatte** [comment]
> https://github.com/uiwjs/react-codemirror/blob/588b8b9c11afda8ad360b9cc8606b3a16234ee6b/src/index.js#L33-L38
> 
> 通过 ref 能获取到 `codemirror` 和 `editor` 对象

可以发个例子吗？
