### ISSUE TITLE
Support `tags.standard(tags.tagName)` in Theme Editor

### ISSUE THREAD

**Issue by karlhorky** [uiwjs/react-codemirror#430]
In the [Theme Editor](https://uiwjs.github.io/react-codemirror/#/editor/theme/single), it would be nice to have the ability to style [the new `tags.standard(tags.tagName)` tokens](https://github.com/lezer-parser/javascript/releases/tag/1.1.0) (introduced because of [this issue](https://github.com/codemirror/dev/issues/956)):

![Screenshot 2022-12-09 at 18 40 42](https://user-images.githubusercontent.com/1935696/206773864-33c524c5-75a7-46ea-bf3e-16a7d792c7e1.png)

Maybe called "tagNameStandard"?

**Comment by jaywcjlove** [comment]
@karlhorky I added this functionality, thx!

**Comment by karlhorky** [comment]
Great thanks!
