### ISSUE TITLE
Codemirror component grows outside of parent with height 100% and overflow auto

### ISSUE THREAD

**Issue by batmilkyway** [uiwjs/react-codemirror#434]
I'm using Chakra UI, but here's a codesandbox that illustrates what I mean

https://codesandbox.io/s/confident-tess-u7r9hv?file=/src/App.tsx

The main thing is
```
export default function App() {
  const filler = [...Array(100).keys()].join("\n");
  return (
    <Box height={"100vh"}>
      <SimpleGrid columns={2} minH={"300px"} height={"100%"} border={"1px"}>
        <Box overflow={"auto"} height={"100%"}>
          <LoremIpsum p={5} />
        </Box>
        <CodeMirror
          height={"100%"}
          value={filler}
          extensions={[
            EditorView.baseTheme({
              "&": { overflow: "auto" },
              "&.cm-editor": { overflow: "auto" },
              ".cm-scroller": { overflow: "auto" }
            })
          ]}
        />
      </SimpleGrid>
    </Box>
  );
}
```
I'm trying a whole bunch of things here, but I can't seem to get anything to respect the overflow directive. I've tried wrapping codemirror in a `Box` (which is `div` under the hood) but then it doesn't even grow.

My goal is to have both columns independently scrollable.

**Comment by jaywcjlove** [comment]
@batmilkyway I don't understand, what's wrong with the example.

**Comment by batmilkyway** [comment]
Thanks for the reply :smile: 

I updated the example a little bit to hopefully show what I mean

```
export default function App() {
  const filler = [...Array(100).keys()].join("\n");
  return (
    <Box height={"100vh"}>
      <SimpleGrid columns={2} minH={"300px"} height={"100%"} border={"1px"}>
        <Box overflow={"auto"} height={"100%"}>
          <LoremIpsum p={5} />
        </Box>
        <CodeMirror
          height={"100%"}
          // value={filler}
          extensions={[
            EditorView.baseTheme({
              "&": { overflow: "auto" },
              "&.cm-editor": { overflow: "auto" },
              "cm-editor": { overflow: "auto" },
              //".cm-content": {overflow: "auto"},
              ".cm-scroller": { overflow: "auto" }
            })
          ]}
        />
      </SimpleGrid>
      <Box>Something goes here</Box>
      <Box>Something goes here</Box>
      <Box>Something goes here</Box>
      <Box>Something goes here</Box>
      <Box>Something goes here</Box>
    </Box>
  );
}
```
When you uncomment `value={filler}` the editor will grow outside of the grid boundaries and over the other `<Box>`es below it, depending on what the browser size is.

**Comment by jaywcjlove** [comment]
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/1680273/208243514-d79931e8-d2bd-4de1-b718-f3943b15eceb.png">

I still don't understand.
@batmilkyway

**Comment by batmilkyway** [comment]
Yea, when I grow my browser window big enough I get the same thing


![Screenshot 2022-12-17 091628](https://user-images.githubusercontent.com/116116609/208253601-9613acf6-9c4e-461e-a70b-f30681094346.png)



But if I shrink the browser window even a little bit then it happens


![Screenshot 2022-12-17 091730](https://user-images.githubusercontent.com/116116609/208253641-2b4654f8-ff2c-4529-8e9a-eda0566bdcd3.png)

Does this not happen with you? I tried it on chrome and safari, it also happens on iOS safari

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/uiwjs-react-codemirror-issues-434-trg60f?fontsize=14&hidenavigation=1&theme=dark

@batmilkyway it's a matter of style

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/1680273/208276012-82e8069f-ee80-4304-bbc8-0138a53a5297.png">

**Comment by batmilkyway** [comment]
I see what you mean now, thank you. That gets me pretty close to what I want so I will go ahead and close this.
