### ISSUE TITLE
Bidirectional input (Right to Left / direction RTL)

### ISSUE THREAD

**Issue by SaadBazaz** [uiwjs/react-codemirror#440]
Hi!
Thanks for this awesome repo. I need bidirectional typing in a Code Editor. It seems like vanilla CodeMirror supports it (https://codemirror.net/5/doc/manual.html, https://codemirror.net/5/demo/bidi.html), but I can't seem to find the option in the React version. How to enable it?

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/tree/v3

@SaadBazaz  use @uiw/react-codemirror@v3

```bash
npm i @uiw/react-codemirror@3.2.9
```

**Comment by jaywcjlove** [comment]
- https://discuss.codemirror.net/t/rtl-support-per-block-in-mixed-rtl-ltr-content/4151
- https://discuss.codemirror.net/t/does-codemirror-6-support-rtl-per-block-paragraph/5120/2

**Comment by jaywcjlove** [comment]
- https://discuss.codemirror.net/t/is-there-an-example-or-perlinetextdirection/5245

**Comment by SaadBazaz** [comment]
Worked by just setting:
```
<CodeMirror
style={{
    direction: "rtl"
}}
/>
```
