### ISSUE TITLE
useCodeMirror overwrites content if not provided via prop

### ISSUE THREAD

**Issue by mrdrogdrog** [uiwjs/react-codemirror#441]
# Greetings
Hello :wave: Nice work. :heart: 

# Problem
In `useCodeMirror.ts` you have an effect which overwrites the document content every time the variable `value` changes. 
I use the react-codemirror component in a project where the content comes from a codemirror extension and not via your prop but the effect still triggers on init and overwrites my initial content.

# Prefered solution
I can't provide the content via the prop so it would be nice to disable this effect. Please don't execute the dispatch in the effect if no content (null or undefined) was given.

**Comment by jaywcjlove** [comment]
@mrdrogdrog Welcome to submit PR

**Comment by mrdrogdrog** [comment]
@jaywcjlove Very gladly! I'm creating it right now

**Comment by jaywcjlove** [comment]
@mrdrogdrog  upgrade `v4.19.5`
