### ISSUE TITLE
Can't init a theme with partial options in TypeScript

### ISSUE THREAD

**Issue by IGassmann** [uiwjs/react-codemirror#444]
When trying to init a theme and passing partial options, TypeScript throws an error because the `theme` and `styles` properties are marked as required in the interface `CreateThemeOptions`. This can be reproduced with the following:

```ts
import { materialInit } from '@uiw/codemirror-theme-material';

<CodeMirror
  theme={materialInit({
    settings: {
      caret: '#c6c6c6',
      fontFamily: 'monospace',
    }
  })}
/>
```

**Comment by jaywcjlove** [comment]
@IGassmann Upgrade `v4.19.6`

**Comment by IGassmann** [comment]
@jaywcjlove latest version only partially solves the issue because it uses `Partial<CreateThemeOptions>` instead of something like [`PartialDeep<T>`](https://github.com/sindresorhus/type-fest/blob/main/source/partial-deep.d.ts). Due to that, the example above still doesn't work because it isn't providing the value `settings.foreground`, which is marked as required by the `CreateThemeOptions['settings']` type.

**Comment by jaywcjlove** [comment]
@IGassmann Upgrade `v4.19.7`

**Comment by IGassmann** [comment]
Solved.
