### ISSUE TITLE
Editor css breaks on navigating away

### ISSUE THREAD

**Issue by mohsinamjad** [uiwjs/react-codemirror#447]
Hi, 
I'm facing one issue which occurs when you navigate away by switching to another tab and then switching it back. the rendered editor css gets broken. 
I'm using it in nextjs with dynamic loading of component with disabled ssr
```Js
const Editor: React.ComponentType<ReactCodeMirrorProps> = dynamic(
  async () => {
    const CodeMirror = await import('@uiw/react-codemirror');
    return CodeMirror;
  },
  { ssr: false },
);

```
versions
```json
    "@uiw/codemirror-theme-github": "^4.19.6",
    "@uiw/react-codemirror": "^4.19.6",
```
browser: Chrome
****Note**: Only happens in mac**

https://user-images.githubusercontent.com/32832044/213674285-c8a1951d-868a-4f79-b642-dd70fa877712.mov

**Comment by jaywcjlove** [comment]
@mohsinamjad Didn't understand what the problem was.

**Comment by mohsinamjad** [comment]
So basically the editor styles gets broken when you switch chrome tabs.
e.g
1. open two tabs on chrome one for your site and other for google or anything.
2. visit the page where you are rendering editor
3. switch to google tab, then open you site tab again and the css gets broken,

**Comment by alexcracea** [comment]
@mohsinamjad I'm having a similar issue, what was the problem cause for you?
