### ISSUE TITLE
Custom Autocomplete.

### ISSUE THREAD

**Issue by stefan1968** [uiwjs/react-codemirror#450]
Not sure this is the right place to ask, but is it possible to override the autocomplete to be a custom react component for certain completions? I.e a react-date picker or something?

**Comment by jaywcjlove** [comment]
@stefan1968 This needs to define an extensions, currently there is no plan, because the workload is a bit heavy.

**Comment by jaywcjlove** [comment]
You can refer to [`color`](https://github.com/uiwjs/react-codemirror/tree/master/extensions/color) to expand.

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/579#issuecomment-1732270138
