### ISSUE TITLE
How to override line numbers?

### ISSUE THREAD

**Issue by rohitcoder** [uiwjs/react-codemirror#453]
I want to show only 5 to 10 lines of source code from a file using this library, I also need to show the line numbers of those source codes, my question is, is there any way to modify existing continuous lines numbers;

In my case scenario, it'll start from 10 to 15 if I want to show a code snippet, it won't start from from 0 or 1

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/714942aeb305d89bc730ea59e7e086717aab629b/extensions/line-numbers-relative/src/index.ts#L4-L20
@rohitcoder 

Example: Gutters https://codemirror.net/examples/gutter/
