### ISSUE TITLE
Disable find/replace behaviour and use browser default

### ISSUE THREAD

**Issue by UhMarco** [uiwjs/react-codemirror#464]
Rather than seeing this:
![replace](https://user-images.githubusercontent.com/52924494/222932014-fbff30ca-fb1e-4296-bf5d-d6140abe76cd.png)

I'd like codemirror to use the browser default which looks like this:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/52924494/222932036-90b3540f-5d59-495f-9ef7-a976f6e3f955.png">

Is this possible?

**Comment by jaywcjlove** [comment]
@UhMarco 

```diff 
import CodeMirror from '@uiw/react-codemirror';

function App() {
  return (
    <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      basicSetup={{
+        searchKeymap: false,
      }}
    />
  );
}
```

**Comment by UhMarco** [comment]
Thank you
