### ISSUE TITLE
Getting cm editor instance and swapping doc

### ISSUE THREAD

**Issue by UhMarco** [uiwjs/react-codemirror#468]
I've seen previous, similar questions but I'm not sure they're providing what I'm after. I'd like an instance of code mirror where I can run methods such as `cm.getDoc()` and `cm.swapDoc()` as seen in the documentation here:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/52924494/223813160-423e0aba-275c-4deb-96ef-b2666723effe.png">
Could anyone clear this up for me?

**Comment by UhMarco** [comment]
I've realised I was looking at version 5 documentation. What's the version 6 equivalent?

**Comment by jaywcjlove** [comment]
What version are you sure you are using?

**Comment by UhMarco** [comment]
> What version are you sure you are using?

Latest

**Comment by jaywcjlove** [comment]
@UhMarco https://codesandbox.io/embed/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-468-it0dlh?fontsize=14&hidenavigation=1&theme=dark

```jsx
import CodeMirror from "@uiw/react-codemirror";
import { StreamLanguage } from "@codemirror/language";
import { shell } from "@codemirror/legacy-modes/mode/shell";
import { useEffect, useRef } from "react";

const code = `x = 10`;

export default function App() {
  const ref = useRef();
  useEffect(() => {
    console.log("ref:", ref.current);
  }, []);
  return (
    <CodeMirror
      ref={ref}
      value={code}
      height="200px"
      readOnly={false}
      extensions={[StreamLanguage.define(shell)]}
      onChange={(value, viewUpdate) => {
        console.log("value:", value);
      }}
    />
  );
}

``

**Comment by jaywcjlove** [comment]
@UhMarco You need to check the [**`CM 6`**](https://codemirror.net/docs/) documentation for this.

**Comment by UhMarco** [comment]
@jaywcjlove Perhaps if I give some more context you'll be able to point me in the right direction. The way I'm currently swapping between notes is just by setting the content. If I perform an undo command, the content goes back to the previous note. From my understand `swapDoc()` would have been what I needed to prevent this from happening and also keep other notes in memory. Is there an equivalent for version 6? I have read through the docs you sent and have not seen something directly similar.

**Comment by jaywcjlove** [comment]
https://discuss.codemirror.net/

@UhMarco Possibility to ask questions to the CM author.

**Comment by UhMarco** [comment]
Solved, thanks for your help.
https://discuss.codemirror.net/t/swapdoc-v6-equivalent/5973
