### ISSUE TITLE
how to set the lineWrapping?

### ISSUE THREAD

**Issue by lmymoonsky** [uiwjs/react-codemirror#486]
This is This is the original configuration：
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  mode: "application/xml",
  styleActiveLine: true,
  lineNumbers: true,
  lineWrapping: true,
});

This is [react-codemirror] configuration, But I can't find this configuration ，Please take a look 
 <CodeMirror
      value="console.log('hello world!');"
      height="200px"
      extensions={[javascript({ jsx: true })]}
      onChange={onChange}
    />

**Comment by jaywcjlove** [comment]
@lmymoonsky 

- https://github.com/uiwjs/react-codemirror/issues/274#issuecomment-1060137121
