### ISSUE TITLE
v3: Undo on first load clears the editor

### ISSUE THREAD

**Issue by sankargorthi** [uiwjs/react-codemirror#489]
In the v3 version of the editor wrapper, when I perform the undo action after the value is loaded into the editor, the value is cleared and the editor is emptied. This can be reproduced on the [example page](https://raw.githack.com/uiwjs/react-codemirror/doc3/index.html).

**Comment by jaywcjlove** [comment]
@sankargorthi Upgrade `v3.2.10`

**Comment by sankargorthi** [comment]
Thanks for the merge! Closing as resolved.
