### ISSUE TITLE
使用后多出上百个chunk文件

### ISSUE THREAD

**Issue by zhenxianluo** [uiwjs/react-codemirror#5]

**Comment by zhenxianluo** [comment]
webpack版本3.8.1

**Comment by jaywcjlove** [comment]
@zhenxianluo 这个问题我无能为力，你应该检查你的 webpack 打包规则。看 https://uiwjs.github.io/react-codemirror/ 它只有 3 个 chunk。

**Comment by zhenxianluo** [comment]
换成react-codemirror2已经好了, 谢谢

**Comment by luguosheng1314** [comment]
遇到同样的问题 用2.x版本也会这样

**Comment by jaywcjlove** [comment]
@luguosheng1314 这个是他的语言包。没有将所有的语言合并。

**Comment by hua1995116** [comment]
代码中不应该 import(`codemirror/mode/${mode.mode}/${mode.mode}.js`) 这样引入，因为webpack 无法动态确定具体引入哪个 js，因此会把  mode 下的所有文件都打包进去，建议这个引入交给用户吧。 @jaywcjlove

**Comment by jaywcjlove** [comment]
@hua1995116 我们这边的应用场景是，不确定要支持哪个语言，需要按需自动加载

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/bafa5ddde116f1b41e05b1825376c45863606791/.kktrc.js#L31-L35

配置 webpack 减少 chunk 输出。
