### ISSUE TITLE
Adding a vim plugin

### ISSUE THREAD

**Issue by kimfucious** [uiwjs/react-codemirror#503]
I Googled this and came up with nothing, so I don't know if it's even possible.

I'd like to add a vim plugin, for example Tim Pope's [vim-surround](https://github.com/tpope/vim-surround), to react-codemirror.

Any help would be most appreciated!

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/501#issue-1714879070

@kimfucious  I see that the problem you mentioned is using the vim [@replit/codemirror-vim](https://www.npmjs.com/package/@replit/codemirror-vim) plugin.

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/331#issuecomment-1155264375

**Comment by jaywcjlove** [comment]
@kimfucious I think this is very difficult, and I don't know any way to integrate them.
