### ISSUE TITLE
Add Elixir support

### ISSUE THREAD

**Issue by Qodestackr** [uiwjs/react-codemirror#507]
I am a huge fun of the Elixir language and would like to know if its part of your plans to support it. I would be glad to help implement it. Kindly let me know about it. Having fun with the editor :)

**Comment by jaywcjlove** [comment]
@Qodestackr https://codesandbox.io/embed/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-507-uzbywp?fontsize=14&hidenavigation=1&theme=dark

```jsx
import React from "react";
import CodeMirror from "@uiw/react-codemirror";
import { StreamLanguage } from "@codemirror/language";
import { elixir } from "codemirror-lang-elixir";

const lang = StreamLanguage.define(elixir);

const codeStr = `children = [
  TCP.Pool,
  {TCP.Acceptor, port: 4040}
]

Supervisor.start_link(children, strategy: :one_for_one)`;

export default function App() {
  const onChange = React.useCallback((value, viewUpdate) => {
    console.log("value:", value);
  }, []);
  return (
    <div>
      <CodeMirror
        value={codeStr}
        height="200px"
        theme="dark"
        extensions={[lang]}
        onChange={onChange}
      />
      <CodeMirror
        value={codeStr}
        height="200px"
        extensions={[lang]}
        onChange={(value, viewUpdate) => {
          console.log("value:", value);
        }}
      />
    </div>
  );
}
```

**Comment by Qodestackr** [comment]
Thanks for this. My bad I can as trying/lang-elixir.. but Why inconsistent naming of packages 📦?

**Comment by jaywcjlove** [comment]
@Qodestackr [`codemirror-lang-elixir`](https://www.npmjs.com/package/codemirror-lang-elixir) This package comes from a third-party personal package, not from codemirror official

**Comment by Qodestackr** [comment]
Thank you I now get. Ping me for any fun project you might be maintaining or need collaboration 😁✍️
