### ISSUE TITLE
Questions on Merge

### ISSUE THREAD

**Issue by kimfucious** [uiwjs/react-codemirror#508]
I'm trying to compare two markdown files, using CodeMirrorMerge.

In brief, I'm comparing text stored in local storage with text in React state, in the case when the browser is closed before an item is saved.

The documentation is a bit sparse, so I need a bit of help.  Any helpful advice would be most appreciated.

Using the documentation [here](https://uiwjs.github.io/react-codemirror/#/merge/document), I've managed to produce what's shown in this screenshot:
![image](https://github.com/uiwjs/react-codemirror/assets/26792769/2df9560d-5ded-4e2b-8764-8295428bd19d)
In this example the text is a single "paragraph" of around 60 words.  In practice, there will be many more paragraphs with more or less words.

The "original" text is on the left, and the "modified" is on the right.  I want to potentially merge changes that are in modified to the original.

Question 1:  Is there any way to wrap the text?  It's near impossible to compare long lines (i.e. paragraphs) on a single line.

With `CodeMirror` from `@uiw/react-codemirror`, I can wrap text with the following code:
```js
extensions={[
    vim({ status: true }),
    markdown(),
    EditorView.lineWrapping, // <= right here
    EditorView.contentAttributes.of({ spellcheck: "true" }),
]}
```
The wrapping looks like this:
![image](https://github.com/uiwjs/react-codemirror/assets/26792769/f205b5db-fd7c-4309-8b0f-7b7097085565)

I can't see a way to do this with CodeMirrorMerge.

Question 2:  Is there a way to adjust the theme?  

Question 3:  What are those vertical white lines?

Question 4:  How to you perform merges?  In the screen shot below (from [here](https://codemirror.net/5/demo/merge.html)), there's a little arrow, that when clicked on performs the merge.  I can't seem to make that arrow show with what I've tried.

![image](https://github.com/uiwjs/react-codemirror/assets/26792769/f79fcc33-3d25-4232-9834-43d25c7d8204)
Question 5:  When a merge is actually performed, how can I get that value, so as to save it somewhere?

Here's the code for the component as it stands.
```ts
import { EditorState } from "@codemirror/state";
import { EditorView } from "codemirror";
import { Scene } from "../../../types";
import { useMemo } from "react";
import CodeMirrorMerge from "react-codemirror-merge";
import config from "../../../config/config.json";

const Original = CodeMirrorMerge.Original;
const Modified = CodeMirrorMerge.Modified;

interface Props {
    originalScene: Scene | undefined;
}
// https://uiwjs.github.io/react-codemirror/#/merge/onchange
export default function MergeEditor({ originalScene }: Props) {
    const { original, modified } = useMemo(() => {
        let modified = "";
        const original = originalScene?.text;
        const draftInStorage = localStorage.getItem(config.DRAFT_SCENE_KEY);
        if (draftInStorage) {
            modified = JSON.parse(draftInStorage).text;
        }
        return { original, modified };
    }, [originalScene]);
    return (
        <CodeMirrorMerge orientation="a-b" highlightChanges>
            <div style={{ maxWidth: 300 }}>
                <Original value={original} />
            </div>
            <div style={{ maxWidth: 300 }}>
                <Modified
                    value={modified}
                    extensions={[
                        EditorView.editable.of(false),
                        EditorState.readOnly.of(true),
                    ]}
                />
            </div>
        </CodeMirrorMerge>
    );
}
```

**Comment by jaywcjlove** [comment]
@kimfucious https://codesandbox.io/embed/react-codemirror-example-codemirror-6-https-github-com-uiwjs-react-codemirror-issues-508-0l7067?fontsize=14&hidenavigation=1&theme=dark

```tsx
import React, { useState } from "react";
import CodeMirrorMerge from "react-codemirror-merge";

const Original = CodeMirrorMerge.Original;
const Modified = CodeMirrorMerge.Modified;
let doc = `one
two
three
four
five`;

export default function App() {
  const [value, setValue] = useState();
  const onChange = React.useCallback((val) => {
    console.log("value:", val);
    setValue(val);
  }, []);
  return (
    <div>
      <CodeMirrorMerge revertControls="a-to-b">
        <Original value={doc} onChange={onChange} />
        <Modified
          value={doc.replace(/t/g, "T") + "Six"}
          onChange={(val) => {
            console.log("value:222:", val);
          }}
        />
      </CodeMirrorMerge>
      <pre>{value}</pre>
    </div>
  );
}
```

**Comment by kimfucious** [comment]
Hi @jaywcjlove, thanks for the response.

I believe what you're showing me is how to get the change value from the merge.

If so, that answers Question 5, but the rest are still outstanding.

**Comment by jaywcjlove** [comment]
@kimfucious Both `Original` and `Modified` have `onChange`. I don't know what you need to save?

You can listen for changes and then save the text you want.
