### ISSUE TITLE
How to wrap text in CodeMirrorMerge?

### ISSUE THREAD

**Issue by kimfucious** [uiwjs/react-codemirror#514]
I'm trying to compare two markdown files, using CodeMirrorMerge.

Using the documentation [here](https://uiwjs.github.io/react-codemirror/#/merge/document), I've managed to produce what's shown in this screenshot:
![image](https://github.com/uiwjs/react-codemirror/assets/26792769/2df9560d-5ded-4e2b-8764-8295428bd19d)
In this example the text is a single "paragraph" of around 60 words.  In practice, there will be many more paragraphs with more or less words.

The "original" text is on the left, and the "modified" is on the right.  I want to potentially merge changes that are in modified to the original.

**Question:**  Is there any way to wrap the text?  It's near impossible to compare long lines (i.e. paragraphs) on a single line?

With `CodeMirror` from `@uiw/react-codemirror`, I can wrap text with the following code:
```js
extensions={[
    vim({ status: true }),
    markdown(),
    EditorView.lineWrapping, // <= right here
    EditorView.contentAttributes.of({ spellcheck: "true" }),
]}
```
The wrapping looks like this:
![image](https://github.com/uiwjs/react-codemirror/assets/26792769/f205b5db-fd7c-4309-8b0f-7b7097085565)

I can't see a way to do this with CodeMirrorMerge.

**Comment by jaywcjlove** [comment]
@kimfucious https://codesandbox.io/embed/nostalgic-rgb-gj6kfz?fontsize=14&hidenavigation=1&theme=dark

Upgrade `v4.20.3`

```jsx
import React, { useState } from "react";
import CodeMirrorMerge from "react-codemirror-merge";
import { EditorView } from "@codemirror/view";

const Original = CodeMirrorMerge.Original;
const Modified = CodeMirrorMerge.Modified;
let doc = `one
two
threethreethreethreethreethreethreethreethreethreethreethree
four
five`;

export default function App() {
  const [value, setValue] = useState("");
  const [valueModified, setValueModified] = useState("");
  return (
    <div>
      <CodeMirrorMerge orientation="a-b">
        <Original
          extensions={[EditorView.lineWrapping]}
          onChange={(value) => {
            setValue(value);
          }}
          value={doc}
        />
        <Modified
          extensions={[EditorView.lineWrapping]}
          onChange={(value) => {
            setValueModified(value);
          }}
          value={doc.replace(/t/g, "T") + "Six"}
        />
      </CodeMirrorMerge>
      <div style={{ display: "flex" }}>
        <pre style={{ flex: 1 }}>{value} </pre>
        <pre style={{ backgroundColor: "#fff", flex: 1 }}>{valueModified} </pre>
      </div>
    </div>
  );
}
```

- https://github.com/uiwjs/react-codemirror/issues/274#issuecomment-1060137121

**Comment by kimfucious** [comment]
Hi @jaywcjlove.

That's perfect!  Thanks much for the help.

I didn't realize that you could add extensions to `Original` and `Modified`
