### ISSUE TITLE
How to remove vertical lines in CodeMirrorMerge

### ISSUE THREAD

**Issue by kimfucious** [uiwjs/react-codemirror#516]
I'm trying to compare two markdown files, using CodeMirrorMerge.

**Question 3:**  What are those vertical lines that stick up on the left of the original and modified blocks, and how can I get rid of them?

![image](https://github.com/uiwjs/react-codemirror/assets/26792769/f976d606-2f66-4113-8853-10f6dc54ff42)

Here's the code:
```ts
import { EditorState } from "@codemirror/state";
import { EditorView } from "codemirror";
import { Scene } from "../../../types";
import CodeMirrorMerge from "react-codemirror-merge";

const Original = CodeMirrorMerge.Original;
const Modified = CodeMirrorMerge.Modified;

interface Props {
    changedText: string;
    setChangedText: (s: string) => void;
    originalScene: Scene | undefined;
    original: string | undefined;
    modified: string | undefined;
}
// https://uiwjs.github.io/react-codemirror/#/merge/onchange
export default function MergeEditor({
    original,
    modified,
    changedText,
    setChangedText,
}: Props) {
    function handleChange(str: string) {
        console.log("Changed Text", str);
        setChangedText(str);
    }

    return (
        <div className="container d-flex flex-column align-items-center w-100">
            <CodeMirrorMerge
                className="w-100"
                highlightChanges
                orientation="a-b"
                revertControls="b-to-a"
            >
                <Original
                    value={original}
                    onChange={(str) => handleChange(str)}
                />
                <Modified
                    value={modified}
                    extensions={[
                        EditorView.editable.of(false),
                        EditorState.readOnly.of(true),
                    ]}
                />
            </CodeMirrorMerge>

            <div className="d-flex justify-content-between w-100">
                <small>Current Scene</small>
                <small>Unsaved Changes</small>
            </div>
            {changedText !== modified && (
                <div className="d-flex justify-content-center mt-3 w-100">
                    You can merge the unsaved changes by clicking the little
                    arrow
                </div>
            )}
        </div>
    );
}
```

**Comment by jaywcjlove** [comment]
```diff
<CodeMirrorMerge
+  gutter={false}
 >
```

![image](https://github.com/uiwjs/react-codemirror/assets/1680273/e856cefc-429a-4c89-b026-df2adea19a8a)

Is it the vertical line on the screenshot? @kimfucious

**Comment by kimfucious** [comment]
Hi @jaywcjlove.

Thanks for your assistance.

`gutter={false}` works to remove the lines protruding from the top, but it also removes the entire gutter.

For my use case, this is okay.  Ideally, it would be nice to keep the gutter to highlight the diffs.

**Comment by jaywcjlove** [comment]
<img width="1269" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/f4c331eb-3561-4a16-958f-311ba5ec9256">

I didn't understand your question exactly. https://codesandbox.io/embed/https-github-com-uiwjs-react-codemirror-issues-516-0pxrih?fontsize=14&hidenavigation=1&theme=dark

**Comment by kimfucious** [comment]
Hi @jaywcjlove.

I'm talking about this:

![image](https://github.com/uiwjs/react-codemirror/assets/26792769/639c4a3c-17c9-4749-b524-3dbc72a563cc)

The gutter, when not set to false, produces a line above both Original and Modified.

**Comment by jaywcjlove** [comment]
<img width="1182" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/8d1f2c5d-0254-4251-888a-5ae7c7b8d95f">

@kimfucious I'm not sure where the problem is.

**Comment by kimfucious** [comment]
It's okay, @jaywcjlove.

I can live without the gutter on this one.

Thanks for your help.

**Comment by kimfucious** [comment]
I'm thinking that those lines are showing due to duplicate codeMerge elements being loaded.

I've mentioned that here: #517.
