### ISSUE TITLE
Does `autocompletion` work on the demo site?

### ISSUE THREAD

**Issue by Zeng1998** [uiwjs/react-codemirror#518]
Hello, thanks for your working. I want to know does the  `autocompletion` work? Or do I need to configure something else?

https://github.com/uiwjs/react-codemirror/assets/31177490/1854151f-71e3-4bdf-ae29-594b020fe4d1

https://streamja.com/aN1Me

**Comment by jaywcjlove** [comment]
@Zeng1998 I can't view the video, so I don't know what problem you describe.

**Comment by Zeng1998** [comment]
@jaywcjlove  https://streamja.com/aN1Me That's the external link of the video.

**Comment by Zeng1998** [comment]
https://github.com/uiwjs/react-codemirror/assets/31177490/e85014df-7e07-42c4-91de-7e7db96679e4

@jaywcjlove  I have uploaded the video. Please take a look.

**Comment by jaywcjlove** [comment]
@Zeng1998  Do you need code hinting?

Here is the official documentation you can give it a try. => https://codemirror.net/examples/autocompletion/

**Comment by Zeng1998** [comment]
> @Zeng1998 Do you need code hinting?
> 
> Here is the official documentation you can give it a try. => https://codemirror.net/examples/autocompletion/

It seems that it can only provide some (not comprehensive) keyword completion by default. 

Actually I thought @codemirror/lang-xxx can provide full completion/hints but it doesn't seem to work.
