### ISSUE TITLE
How to disable indent by tab key 

### ISSUE THREAD

**Issue by 18888628835** [uiwjs/react-codemirror#544]
when I key down the `tab` key , I hope tabIndex  will be valid  instead of indent.
by default,codeMirror do not support indent by `tab` key, but `React-codeMirror` do.
Is there a option to disable indent by tab key?

**Comment by 18888628835** [comment]
oh... I found a option of props called `indentWithTab` . so I think this issue could be closed

**Comment by jaywcjlove** [comment]
@18888628835 

https://github.com/uiwjs/react-codemirror/blob/660d308083d5b6506c84de4aec32063b3ad51a13/core/src/index.tsx#L48-L53

**Comment by 18888628835** [comment]
> 

thank you. I'm sorry for my carelessness
