### ISSUE TITLE
Theme selection color

### ISSUE THREAD

**Issue by guillermoamaral** [uiwjs/react-codemirror#546]
Hi,

I'm trying to use "selection" theme property to change the selection background color. However, it does not take effect (as the selectionMatch does).

https://codesandbox.io/s/damp-platform-tqn22j?file=/src/App.js

(I used a dark background on purpose, first because I want to use it in my app, and secondly because the issue is more notorious; however, you can change the configuration to use a light them, with a white background for instance, and you'll see that the selection color is not applied; what it is honored is the match selection color).

Thanks!

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/jolly-mclaren-gyp3h5?fontsize=14&hidenavigation=1&theme=dark

@guillermoamaral I'm not sure what the problem is, I tested that the colors display normally.

**Comment by guillermoamaral** [comment]
@jaywcjlove Essentially you don't get the color you set.

**Comment by guillermoamaral** [comment]
![Screenshot_20230728_014708_Chrome](https://github.com/uiwjs/react-codemirror/assets/43265642/5836417f-878e-467b-bee3-868dd8b4be09)
The background color of the text selected (on the left) cannot be changed, and for some backgrounds is almost undistinguishable. On the right you see the cyan set as selectionMatch.

**Comment by jaywcjlove** [comment]
@guillermoamaral Upgrade `v4.21.9`
