### ISSUE TITLE
ReferenceError: require is not defined in @babel/runtime/helpers/esm/extends.js

### ISSUE THREAD

**Issue by yi-you** [uiwjs/react-codemirror#554]
## Description

I'm encountering a `ReferenceError: require is not defined` error in my Vue project when building with Webpack. The error occurs in the `@babel/runtime/helpers/esm/extends.js` file.

## Environment

- **Vue version:** 2.6.10
- **Webpack version:** 5.88.2
- **Babel version:** 7.22.10
- **Node.js version:** 16.20.1
- **OS:** Windows 10

## Error Details

```
ReferenceError: require is not defined
    at ./node_modules/@babel/runtime/helpers/esm/extends.js (extends.js:3:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@uiw/codemirror-theme-github/esm/index.js (chunk-vendors.cf2ca45f-2.1.7.js:19:88)
```

**Comment by jaywcjlove** [comment]
> Vue version: 2.6.10 ?????

@yi-you Can it run in vue?

**Comment by jaywcjlove** [comment]
@yi-you 

- https://github.com/vitejs/vite/issues/3409
- https://www.npmjs.com/package/vite-plugin-require-transform

**Comment by yi-you** [comment]
> > Vue version: 2.6.10 ?????
> 
> @yi-you Can it run in vue?

Yes, it runs normally when I use node12 + webpack4.

**Comment by yi-you** [comment]
> @yi-you
> 
> * [`require is not defined` when importing a node_module that imports a CSS file vitejs/vite#3409](https://github.com/vitejs/vite/issues/3409)
> * https://www.npmjs.com/package/vite-plugin-require-transform

emm, I'm using vue-cli 5.0.8 😂
I'm going to check how to upgrade to Vite.

**Comment by yi-you** [comment]
Is the codemirror-theme-github compatible with babel7 and webpack5?

**Comment by yi-you** [comment]
Thank you very much. I've also set up a demo to test this theme, and it works perfectly.
