### ISSUE TITLE
onFocusChange is there a replacement?

### ISSUE THREAD

**Issue by marabesi** [uiwjs/react-codemirror#555]
reac-codemirror has the event onFocusChange that I used to use in my project like so:

```jsx
<div className={`editor ${className} `}>
  <CodeMirror
    value={this.props.value}
    options={codeMirrorOptions}
    className="editor"
    onChange={this.props.codeChanged}
    onFocusChange={this.onFocus}
  />
</div>
```

This is what it does: [onFocusChange Function (focused) called when the editor is focused or loses focus](https://github.com/JedWatson/react-codemirror/blob/master/README.md).

But I couldn't find a equivalent to use for @uiw/react-codemirror, is there a workaround for this one?

**Comment by jaywcjlove** [comment]
@marabesi https://uiwjs.github.io/react-codemirror/#/extensions/events

```jsx
import * as events from '@uiw/codemirror-extensions-events';

const extension = events.content({
  focus: (evn) => {
    console.log('focus');
  },
  blur: (evn) => {
    console.log('blur');
  },
});

<CodeMirror value="console.log('hello world!');" height="200px" extensions={[extension]} />
```

**Comment by marabesi** [comment]
checked with extensions and it worked!

Thanks!
