### ISSUE TITLE
UNSAFE components warning.

### ISSUE THREAD

**Issue by goutham8343** [uiwjs/react-codemirror#56]
Shows the following warning:

Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

**Comment by jaywcjlove** [comment]
@goutham8343 Welcome to submit PR. thx!

**Comment by jaywcjlove** [comment]
@goutham8343 Upgrade `+ @uiw/react-codemirror@2.3.2`
