### ISSUE TITLE
Compiled version of the CSS

### ISSUE THREAD

**Issue by OmarZeidan** [uiwjs/react-codemirror#57]
Can you please have the CSS compiled instead of being imported from the `node_modules`

**Where:**
https://github.com/uiwjs/react-codemirror/blob/cd62bbd8861bcbd7fa847b85dd63a1a97b58c31f/src/index.js#L3
And L5

This is causing troubles when we use the library for `next.js`

<3

**Comment by jaywcjlove** [comment]
@OmarZeidan Upgrade `+ @uiw/react-codemirror@2.3.0`

**Comment by OmarZeidan** [comment]
@jaywcjlove Thanks but the same error! 

Look inside `/lib/esm/index.js` file of your compiled version, and you will notice 

```js
import './codemirror.css';
import './index.css';
```

Which will def be causing the error for next.js framework and Global CSS dilemma!

**Comment by jaywcjlove** [comment]
@OmarZeidan Can you give me an example, let me debug it?

**Comment by gdeffo** [comment]
Next.js says this, when I try to use the component.

error - ./node_modules/@uiw/react-codemirror/lib/esm/codemirror.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@uiw/react-codemirror/lib/esm/index.js

Is this a good example? Try to render this component.

```typescript
import Codemirror from "@uiw/react-codemirror";

export default function CodeEditor() {

    function onChange(instance: CodeMirror.Editor, change: CodeMirror.EditorChangeLinkedList[]) {
        console.log('instance :>> ', instance.getValue);
    }

    return <Codemirror
        options={{
            theme: 'monokai',
            keyMap: 'sublime',
            mode: 'jsx',
        }}
        onChange={onChange}
    />
}
```

**Comment by Gnarus-G** [comment]
Next.js says this, when I try to use the component.

error - ./node_modules/@uiw/react-codemirror/lib/esm/codemirror.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@uiw/react-codemirror/lib/esm/index.js

Is this a good example? Try to render this component.

```typescript
import Codemirror from "@uiw/react-codemirror";

export default function CodeEditor() {

    function onChange(instance: CodeMirror.Editor, change: CodeMirror.EditorChangeLinkedList[]) {
        console.log('instance :>> ', instance.getValue);
    }

    return <Codemirror
        options={{
            theme: 'monokai',
            keyMap: 'sublime',
            mode: 'jsx',
        }}
        onChange={onChange}
    />
}
```

**Comment by jaywcjlove** [comment]
@Gnarus-G Since codemirror does not support server-side rendering, it is a bit strange to implement. Upgrade `+ @uiw/react-codemirror@3.0.2`


```jsx
import { useEffect, useState } from 'react';

function HomePage() {
  const [comp, setComp] = useState();
  useEffect(() => {
    if (window) {
      import('@uiw/react-codemirror').then((obj) => {
        if (!comp) {
          setComp(obj.default);
        }
      });
    }
  }, []);

  const Comps = comp;
  return (
    <div>
      <div>Welcome to Next.js!</div>
      {Comps && (
        <Comps
          value="const a = 0;"
          options={{
            mode: "jsx",
          }}
        />
      )}
    </div>
  )
}

export default HomePage
```

```bash
$ yarn add @zeit/next-css
```

Add `next.config.js`

```js
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  // Your configurations here
});
```

**Comment by jaywcjlove** [comment]
@Gnarus-G  Exmaple: https://codesandbox.io/s/nextjs-example-react-codemirror-bimq7?file=/pages/index.js

**Comment by Gnarus-G** [comment]
@jaywcjlove Oh man, I appreciate you. I learned a lot from this. Thank you.

**Comment by matteoturini** [comment]
> @Gnarus-G Since codemirror does not support server-side rendering, it is a bit strange to implement. Upgrade `+ @uiw/react-codemirror@3.0.2`
> 
> ```js
> import { useEffect, useState } from 'react';
> 
> function HomePage() {
>   const [comp, setComp] = useState();
>   useEffect(() => {
>     if (window) {
>       import('@uiw/react-codemirror').then((obj) => {
>         if (!comp) {
>           setComp(obj.default);
>         }
>       });
>     }
>   }, []);
> 
>   const Comps = comp;
>   return (
>     <div>
>       <div>Welcome to Next.js!</div>
>       {Comps && (
>         <Comps
>           value="const a = 0;"
>           options={{
>             mode: "jsx",
>           }}
>         />
>       )}
>     </div>
>   )
> }
> 
> export default HomePage
> ```
> 
> ```shell
> $ yarn add @zeit/next-css
> ```
> 
> Add `next.config.js`
> 
> ```js
> const withCSS = require('@zeit/next-css');
> 
> module.exports = withCSS({
>   // Your configurations here
> });
> ```

@zeit/next-css is deprecated. Can you just remove the imports from the package, and allow us to import it ourselves?
