### ISSUE TITLE
Themes have strange highlighting behavior when selecting text.

### ISSUE THREAD

**Issue by Ethan-Vanderheijden** [uiwjs/react-codemirror#570]
Different themes have different highlight behaviors, and some of them look broken.
All of these bugs were replicated on the [demo preview page](https://uiwjs.github.io/react-codemirror/) using Chrome.

GitHub Light:
When selecting certain characters like spaces and semi-colons, the selected area seems taller than it is supposed to be.
https://github.com/uiwjs/react-codemirror/assets/84098504/1e30fb5b-d19e-477f-9e39-bd8cf420b933

Duotone Light:
No characters on the active line are hlighted except spaces.
https://github.com/uiwjs/react-codemirror/assets/84098504/20494f83-6240-4677-8727-9e4e605c59a7

**Comment by Ethan-Vanderheijden** [comment]
In the theme editor, you can recreate this bug by selecting certain words that are already styled. You'll notice that most text is correctly highlighted but the blue words are not:

![image](https://github.com/uiwjs/react-codemirror/assets/84098504/e12c2236-5001-481a-90b3-6e61112f8a2a)

The problem is that the blue words are styled with ```background-color: transparent !important``` which overrides the selection color.

![image](https://github.com/uiwjs/react-codemirror/assets/84098504/683e802e-ccfb-4486-af2a-0a3b0e82123c)

Ideally, individual elements should not be defining a background color that overrides the selection color.

**Comment by Ethan-Vanderheijden** [comment]
root cause was #573

**Comment by jaywcjlove** [comment]
@Ethan-Vanderheijden Upgrade `v4.21.14`
