### ISSUE TITLE
No matching version found for @uiw/codemirror-theme-aura@4.21.18

### ISSUE THREAD

**Issue by parth391** [uiwjs/react-codemirror#576]
On `npm update` below error is coming.

`npm ERR! code ETARGET`
`npm ERR! notarget No matching version found for @uiw/codemirror-theme-aura@4.21.18.`
`npm ERR! notarget In most cases you or one of your dependencies are requesting`
`npm ERR! notarget a package version that doesn't exist.`

**Comment by jaywcjlove** [comment]
@parth391 This CI did not succeed in the release, let me rerun the CI.

**Comment by jaywcjlove** [comment]
@parth391 Has been published successfully!
