### ISSUE TITLE
urgent ！urgent ！how to fix the build error : node_modules/@codemirror/lint/dist/index.js: Property body expected type of array but got null

### ISSUE THREAD

**Issue by jaydenxiao2016** [uiwjs/react-codemirror#580]
"@codemirror/lang-json": "^6.0.1",
    "@codemirror/lang-html": "^6.4.5",
    "@codemirror/lang-javascript": "^6.1.9",
    "@codemirror/lang-sass": "^6.0.2",
    "@codemirror/lang-xml": "^6.0.2",
   "@uiw/react-codemirror": "^4.21.18",

**Comment by jaywcjlove** [comment]
@jaydenxiao2016 

remove any direct dependencies on raw codemirror (if any) (I have yarn):
yarn remove codemirror

```bash
rm -fr yarn.lock
rm -fr package-lock.json

rm -fr node_modules

yarn install
```

```js
"@codemirror/lang-html": "^6.4.6",
"@codemirror/lang-javascript": "^6.2.1",
```
