### ISSUE TITLE
lint work incorrent in 4.21.19

### ISSUE THREAD

**Issue by hemisu** [uiwjs/react-codemirror#592]
<img width="1099" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/11391390/78d5e261-3f5e-44d5-97bd-43b2178df0b2">
look this not show the diagnose error

**Comment by jaywcjlove** [comment]
@hemisu The `lint` `extension is` not added by default and needs to be added manually.

**Comment by hemisu** [comment]
@jaywcjlove 
https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQgeyBqc29uLCBqc29uUGFyc2VMaW50ZXIgfSBmcm9tICdAY29kZW1pcnJvci9sYW5nLWpzb24nOwppbXBvcnQge2xpbnRlcn0gZnJvbSAiQGNvZGVtaXJyb3IvbGludCIKCm5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICJ7IFwiMVwiOiAxLCwsfVxuIiwKICBleHRlbnNpb25zOiBbYmFzaWNTZXR1cCwganNvbigpLCBsaW50ZXIoanNvblBhcnNlTGludGVyKV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==

add lint but not work well

**Comment by jaywcjlove** [comment]
@hemisu Example: https://codemirror.net/examples/lint/


You can find the solution you need at https://discuss.codemirror.net/.

**Comment by fabpico** [comment]
> @jaywcjlove 
> add lint but not work well

There are missing braces `linter(jsonParseLinter)` -> `linter(jsonParseLinter())`. See [fixed code](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQgeyBqc29uLCBqc29uUGFyc2VMaW50ZXIgfSBmcm9tICdAY29kZW1pcnJvci9sYW5nLWpzb24nOwppbXBvcnQge2xpbnRlcn0gZnJvbSAiQGNvZGVtaXJyb3IvbGludCIKCm5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICJ7IFwiMVwiOiAxLCwsfVxuIiwKICBleHRlbnNpb25zOiBbYmFzaWNTZXR1cCwganNvbigpLCBsaW50ZXIoanNvblBhcnNlTGludGVyKCkpXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK).

But still, the linting is not satisfactory. The minimalistic red arrow in the mittle of the line, and the missing error icon in the line numbers bar. This was also reported here https://discuss.codemirror.net/t/json-linter-ux/3560.

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-codemirror/issues/469#issuecomment-1669184227
