### ISSUE TITLE
How could I realize the same functionality of CodeMirror 5.x sql-hint in CodeMirror6

### ISSUE THREAD

**Issue by wanglufei-567** [uiwjs/react-codemirror#598]
Hi!
When I migrate from  CodeMirror 5.x， I found this situation
CodeMirror 5.x with sql-hint
![image](https://github.com/uiwjs/react-codemirror/assets/53336017/3b5f9e48-0222-4a0c-8e9d-93b0c9c3102b)

CodeMirror 6.x with autoComplete
![image](https://github.com/uiwjs/react-codemirror/assets/53336017/3e81dd84-5e05-4cc7-8816-20f5eb3109c2)

keyword + "." couldn't highlight
DYNAMIC_PARAMS is my custom keyword

so how could I make "DYNAMIC_PARAMS." highlight

**Comment by jaywcjlove** [comment]
@wanglufei-567 Go here to ask -> https://uiwjs.github.io/react-codemirror/
