### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by ezorfa** [uiwjs/react-codemirror#61]
Hi @justjavac @jaywcjlove @snnsnn @xingyuefeng !

Is it possible to have a file manager on the left side of the code editor to show a hierarchy of project files like so http://demo.icecoder.net/ICEcoder/ ?

Thanks

**Comment by jaywcjlove** [comment]
@ezorfa You need to implement your own featrue.

**Comment by jaywcjlove** [comment]
@ezorfa This is an example: https://github.com/uiwjs/npm-unpkg
