### ISSUE TITLE
Error: JSX element type 'CodeMirror' does not have any construct or call signatures

### ISSUE THREAD

**Issue by virtuallyunknown** [uiwjs/react-codemirror#610]
Greetings!

I am trying to give this library a try, but when I try the example provided I get the following errors:

```
JSX element type 'CodeMirror' does not have any construct or call signatures.
```

and

```
'CodeMirror' cannot be used as a JSX component.
  Its type 'typeof import("/home/user/projects/react-codemirror-error/node_modules/@uiw/react-codemirror/cjs/index")' is not a valid JSX element type.
```

My project is using Typescript and ESM (`"type": "module"` in package.json). I created a bare-minimum reproducible repository here and you can see the error at `src/index.tsx`:

https://github.com/virtuallyunknown/react-codemirror-error

Any idea what might be causing this? I've searched for similar issues but I couldn't find anything.

Cheers!

---

EDIT: Okay, I managed to get it working with the `useCodeMirror` hook instead.

**Comment by jaywcjlove** [comment]
@virtuallyunknown How do I run your example?

You can refer to the following example:
https://codesandbox.io/embed/react-codemirror-example-codemirror-6-language-rz4rh?fontsize=14&hidenavigation=1&theme=dark

**Comment by virtuallyunknown** [comment]
@jaywcjlove very interesting, thank you. This seems to fix the problem, and if I recall correctly `Bundler` was introduced in TypeScript 5.2 so I need to do some further reading on it.

Cheers again!

**Comment by chyzwar** [comment]
> @virtuallyunknown modify `tsconfig.json`
> 
> ```diff
> -        "module": "NodeNext",
> +        "module": "ESNext",
> -        "moduleResolution": "NodeNext",
> +        "moduleResolution": "Bundler",
> ```

This only work with if react-codemirrior is part of by bundler application. If react-codemirrior is consumed by a third party package, then ESM definitions are incorrect since they are missing extension.

**Comment by morganney** [comment]
Why was this closed? There is an ESM variant published, yet the types aren't working. We shouldn't have to use `moduleResolution: "bundler"`.
