### ISSUE TITLE
EditorView.lineWrapping keeps growing inside same line number rather than pushing it to next one

### ISSUE THREAD

**Issue by rufatZZ** [uiwjs/react-codemirror#612]
First of all thanks for great library with full of features. Appreciating for the work 🙏🏼 

**Problem**: I'm new to using the library, but noticed one thing. In my code example there is few long lines. I'm using wrap lines extension, but it keeps growing inside same line number (1st line). Shouldn't it push it to new line?  (2,3,4...)

using v4, here is re-producable code example: [https://stackblitz.com/edit/react-vycf3s?file=src%2FApp.js](https://stackblitz.com/edit/react-vycf3s?file=src%2FApp.js)

Screenshot of the issue: 
<img width="750" alt="Screenshot 2023-12-27 at 11 31 49" src="https://github.com/uiwjs/react-codemirror/assets/19148199/5357de7c-2a03-4da1-9676-170ef864bd4b">

**Comment by jaywcjlove** [comment]
<img width="486" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/9470e055-49bf-4426-af1f-a78997ba75b2">

You don't have a line break in your string.

@rufatZZ This is correct

**Comment by rufatZZ** [comment]
@jaywcjlove oh i see. added `\n` fixed issue for this cases. Thanks 🙏🏼
