### ISSUE TITLE
Manually set cursor position

### ISSUE THREAD

**Issue by radim10** [uiwjs/react-codemirror#628]
The problem is that when the vale prop changes the cursor is moved to position 0. I can track the cursor before update with state but how to manually set the cursor of the ReactCodeMirrorRef? 
I tried this but it does not seem to work:
`view.state.changeByRange((range) => ({
    changes: [
      { from: range.from, insert: '**' },
      { from: range.to, insert: '**' },
    ],
    range: EditorSelection.range(range.from + 2, range.to + 2),
  })),`

**Comment by CalvinChiramal** [comment]
Did you figure out why the cursor moves to position 0? I'm facing this same issue.
