### ISSUE TITLE
New theme for console/terminal view?

### ISSUE THREAD

**Issue by dalejo96** [uiwjs/react-codemirror#631]
Hey! I am using the code mirror component as a logger for some information in my current application. 
I was wondering, what do you think about opening a PR with the new theme definition and calling it `terminal` or `console`?

Thanks in advance.

**Comment by jaywcjlove** [comment]
@dalejo96 We are very happy to accept PRs for new theme.

**Comment by dalejo96** [comment]
I opened a PR with the new theme, let me know if you have any comments or questions.
https://github.com/uiwjs/react-codemirror/pull/632

**Comment by jaywcjlove** [comment]
@dalejo96 `v4.21.22` Released

**Comment by dalejo96** [comment]
Thanks @jaywcjlove
