### ISSUE TITLE
Custom JS keyboard

### ISSUE THREAD

**Issue by loc-trinh** [uiwjs/react-codemirror#633]
For coding on mobile app, I would like to use a custom keyboard instead of default iOS keyboard which is not good for coding.

For a textarea component, you can set `inputType='none'` to disable iOS keyboard from popping up. and with onHover or something I figure you probably can pull up a custom coding keyboard.

I was wondering if it's possible to do `inputType='none'` for a CodeMirror instance somehow?

**Comment by jaywcjlove** [comment]
@loc-trinh  If you want to prevent the default keyboard from appearing on mobile devices for a `contenteditable` div, you can use a combination of CSS and JavaScript. For example:

```html
<div id="myEditableDiv" contenteditable="true" style="touch-action: none;"></div>
```

In this example, the [`touch-action: none;`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS property is used to disable touch interactions, which can prevent the default keyboard from appearing on touch devices. However, keep in mind that this approach may have other implications for touch interactions, so you should thoroughly test it based on your specific use case.

<img width="1245" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/d9102a01-db52-4297-88c7-8ca3e299ae71">

You can try the method mentioned above by encapsulating an `extension` to add the `touch-action: none;` style to the `div.cm-content`.


Here's a simple `extension` example below, you can refer to and try it out.

https://github.com/uiwjs/react-codemirror/blob/923c16407843e10dd5221ce0fe224f5a4877975b/extensions/events/src/index.ts#L18-L48

**Comment by loc-trinh** [comment]
Thank you so much for the quick reply, I will give this a try.

**Comment by jaywcjlove** [comment]
@loc-trinh, this is the most basic example [extensions/events](https://github.com/uiwjs/react-codemirror/blob/923c16407843e10dd5221ce0fe224f5a4877975b/extensions/events/README.md). This extension adds events to the div DOM node, allowing you to add properties to it.

**Comment by jaywcjlove** [comment]
@loc-trinh I extended the `extensions-events` plugin.

```js
import { element } from '@uiw/codemirror-extensions-events';

const extension3 = element({
  type: 'content',
  props: {
    inputMode: 'none',
  },
});
```

**Comment by loc-trinh** [comment]
Wow you are fast, thank you!
