### ISSUE TITLE
父组件必须确定高度才能设定CodeMirror高度100%？

### ISSUE THREAD

**Issue by Eliot00** [uiwjs/react-codemirror#638]
```jsx
{/* 无法直接用100% */}
  <Grid xs={6} sx={{ height: 'calc(100vh - 40px)' }}>

      <CodeMirror height="100%" style={{ height: '100%' }} value={value} onChange={onChange} />
  </Grid>
```

**Comment by jaywcjlove** [comment]
@Eliot00 您试一试？

```jsx
<CodeMirror
  value="console.log('hello world!');"
  height="100%"
  style={{ height: "100%" }}
  theme="dark"
  extensions={[javascript({ jsx: true })]}
  onChange={onChange}
/>
```

**Comment by Eliot00** [comment]
> @Eliot00 您试一试？
> 
> ```js
> <CodeMirror
>   height="100%"
>   style={{ height: "100%" }}
> />
> ```

我贴的代码就是height和style都是`100%`呀，只要外层不用固定高度CodeMirror就只会显示一行

**Comment by jaywcjlove** [comment]
> > @Eliot00 您试一试？
> > ```js
> > <CodeMirror
> >   height="100%"
> >   style={{ height: "100%" }}
> > />
> > ```
> 
> 我贴的代码就是height和style都是`100%`呀，只要外层不用固定高度CodeMirror就只会显示一行

不用 codemirror 你用 div 设置 100% 也不能撑开父节点
