### ISSUE TITLE
Nord Theme:  A comment for a selected line is not visible

### ISSUE THREAD

**Issue by massongit** [uiwjs/react-codemirror#642]
https://uiwjs.github.io/react-codemirror/
<img width="1106" alt="スクリーンショット 2024-03-23 22 49 03" src="https://github.com/uiwjs/react-codemirror/assets/15100604/1777f125-224a-49cf-a295-819e3753aa84">

In the Nord theme, a comment for a selected line is not visible because the comment and the selected line are both `#4c566a`.
I think this was caused by https://github.com/uiwjs/react-codemirror/commit/4dcc32b7e2a6843839bf0ca8b5ab1c4baa48ade0.

**Comment by jaywcjlove** [comment]
<img width="433" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/bb621a8e-f8da-47a6-ae63-a745dc15b4a7">

@massongit Upgrade `v4.21.25`
