### ISSUE TITLE
How to show Tooltips in react-codemirror

### ISSUE THREAD

**Issue by sahilatahar** [uiwjs/react-codemirror#646]
Hi, first of all thanks for this amazing editor.

## What i want 
I am building a Realtime collaborative code editor and want to show **multiples tooltips** using line number and position on that line received from others code editor through socket. I just want to show multiple tooltips within editor

## What I Tried
I try to pass tooltips as child inside `<Codemirror>` but tooltips become sibling of `div.cm-editor`. If tooltips goes inside `div.cm-editor`. I can add position relative to `div.editor` , position absolute to tooltips and can show tooltips using others cursor position within editor at specific position.

**Comment by jaywcjlove** [comment]
@sahilatahar  Please refer to the official example: -> https://codemirror.net/examples/tooltip/

**Comment by sahilatahar** [comment]
Thanks @jaywcjlove, I follow the documentation and tooltip is added but I am confused how to pass data as parameter to show in tooltip and also how to create multiple tooltips. Sorry, I am new here
