### ISSUE TITLE
Code highlighting not working

### ISSUE THREAD

**Issue by AniruddhaTupe** [uiwjs/react-codemirror#658]
I'm developing a code editor for Python. But I'm unable to get the syntax highlighting to work.

Following is my code - 

```jsx
import './App.css';
import 'codemirror/lib/codemirror.css';
import 'codemirror/addon/comment/comment';
import 'codemirror/keymap/sublime';
import 'codemirror/theme/monokai.css';
import 'codemirror/theme/dracula.css';
import 'codemirror/mode/python/python.js';
import 'codemirror/mode/jsx/jsx';
import CodeMirror from '@uiw/react-codemirror';
import { useState } from 'react';

const code = "print(\"Hello\")";

function App() {
  return (
    <div className="App">
      <CodeMirror
        value={code}
        options={{
          mode: 'python',
        }}
      />
    </div>
  );
}

export default App;
```

And following is the output - 

<img width="340" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/29420900/87cc16cf-a995-4d1c-ad06-ad276267e4d3">

**Comment by jaywcjlove** [comment]
@AniruddhaTupe Example: https://codesandbox.io/embed/react-codemirror-v3-vgr4n?fontsize=14&hidenavigation=1&theme=dark


- https://github.com/uiwjs/react-codemirror/tree/v3

**Comment by jaywcjlove** [comment]
```diff
<CodeMirror
  value={code}
  options={{
+    theme: "monokai",
    mode: 'python',
  }}
/>
```

**Comment by AniruddhaTupe** [comment]
I copied the exact same example code, but still I can't see syntax highlighting.

Following are the sequence of npm commands I executed if that helps - 
npx create-react-app code-autograder
npm install
npm install codemirror@5
npm install @uiw/react-codemirror

Also attaching the file structure - 
<img width="746" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/29420900/e3699462-cc36-40b1-8590-217ab9b1cdfe">

And attaching the output - 
<img width="288" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/29420900/9b1ec8b2-4306-4d4b-a4c7-5e48bb7e19e0">

**Comment by AniruddhaTupe** [comment]
Ok, it's resolved now. 

Had to run `npm i @codemirror/lang-python`

And then import it - 
`import { python } from '@codemirror/lang-python';`

And then use it - 
`extensions={[python()]}`

**Comment by AniruddhaTupe** [comment]
Ok, it's resolved now. 

Had to run `npm i @codemirror/lang-python`

And then import it - 
`import { python } from '@codemirror/lang-python';`

And then use it - 
`extensions={[python()]}`
