### ISSUE TITLE
Missing deps

### ISSUE THREAD

**Issue by lianghx-319** [uiwjs/react-codemirror#659]
As I use pnpm and prevent hoisted. `@codemirror/view` & `@lezer/highlight` are missing.

Can you add make all package clear without phantom dependencies.

And I think use latest pnpm to install `@uiw/react-codemirror` and any of theme can reproduce

<img width="1465" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/27187946/0a566566-c231-41a8-840b-4af913ad4360">

**Comment by jaywcjlove** [comment]
@lianghx-319 I haven't been able to reproduce the error. If you can provide a reproducible example, I will try to resolve it.

**Comment by lianghx-319** [comment]
Maybe rushjs's or pnpm's or vite's problem. But if the deps were declared, it should be fine.
I will create a reproduce repository this weekend

**Comment by lianghx-319** [comment]
It's seem not working with pnpm v7, just close this issue
