### ISSUE TITLE
Customizing the search menu

### ISSUE THREAD

**Issue by pxsty0** [uiwjs/react-codemirror#666]
What can I do to customize the search window that we open with the "ctrl + f" combinations?

**Comment by jaywcjlove** [comment]
@pxsty0 This is a default feature and can be controlled through `searchKeymap`.

https://github.com/uiwjs/react-codemirror/blob/9e321013fbf30b6f8bce62ffdb9de60c8460f4fb/extensions/basic-setup/src/index.ts#L104-L106

<img width="1023" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/8df55023-4601-4519-91a5-6f55325ea794">

**Comment by jaywcjlove** [comment]
@pxsty0  If you want to customize it, you can refer to the [codemirror/search](https://github.com/codemirror/search) Git repository.
