### ISSUE TITLE
 Editable properties causing loss of code formatting

### ISSUE THREAD

**Issue by lamtuanamc** [uiwjs/react-codemirror#667]
I am encountering an issue with the `editable` and `readOnly` properties in react-codemirror. Both properties are described as disabling editing of the editor content by the user:

```
editable: This disables editing of the editor content by the user.
readOnly: This disables editing of the editor content by the user.
```

However, I have noticed a problem where setting `editable={false}` results in the loss of code formatting when reloading the page. To avoid this, I tried setting only `readOnly={true}`, but this still allows the content to be editable.

Is there a way to ensure that when either `editable={false}` or `readOnly={true}`, the content cannot be edited while maintaining the code formatting?

Thank you for your assistance.

**Comment by jaywcjlove** [comment]
@lamtuanamc This is an internal API provided by `CodeMirror`, and I'm not sure what happened.

https://github.com/uiwjs/react-codemirror/blob/9e321013fbf30b6f8bce62ffdb9de60c8460f4fb/core/src/getDefaultExtensions.ts#L57-L62

**Comment by sb8244** [comment]
I'm seeing this same issue. I don't quite understand because it seems like `readOnly` has no effect on the editor at all. Same issue with loss of formatting. 

I attempted to find some hacks to disable updates (like rejecting via `viewUpdate`), but I haven't found a way so far.

**Comment by sb8244** [comment]
Ah it was a dumb issue for me. @lamtuanamc are you using ProseMirror or something else? Check the `contenteditable` wrapper around codemirror (.cm-content) and ensure there's not a style override. 

I had to add the following CSS to fix it: 

```css
.ProseMirror .cm-content[contenteditable="false"] {
  white-space: pre-wrap;
}
```

**Comment by lamtuanamc** [comment]
@sb8244 
I am using BlockNote as an editor. I tried again, and even without adding your CSS class, just setting the readOnly attribute already prevents content changes.
I don't know the reason either, but it's working correctly now
. I'll note down your comment, thanks!
