### ISSUE TITLE
Need package name for scala language

### ISSUE THREAD

**Issue by IntelligaiaVivek** [uiwjs/react-codemirror#668]
Hi need lang package for scala language like we have 
const languageExtensions: any = {
        yaml: [StreamLanguage.define(yaml)],
        javascript: [javascript()],
        sql: [sql({ dialect })],
        r: [StreamLanguage.define(r)],
        python: [python()],
        json: [json()],
       scala: [] // what to add @jaywcjlove 
    };

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-codemirror/blob/9e321013fbf30b6f8bce62ffdb9de60c8460f4fb/extensions/langs/src/index.ts#L141

@IntelligaiaVivek Is this what you need?
