### ISSUE TITLE
Wrong property key to generate a new theme in the Themes Editor page

### ISSUE THREAD

**Issue by joaopalmeiro** [uiwjs/react-codemirror#669]
Hi! 👋 

One of the property keys to generate a new theme/`Extension` via the `createTheme()`function in the [Themes Editor page](https://uiwjs.github.io/react-codemirror/#/editor/theme/single) is wrong, if I'm correct. [Instead of `dark`](https://github.com/uiwjs/react-codemirror/blob/9e321013fbf30b6f8bce62ffdb9de60c8460f4fb/www/src/pages/theme/editor/themeCode.ts#L202) it should be `theme`. 

Let me know your thoughts and if I can open a PR to fix this key, please. Thanks!

**Comment by jaywcjlove** [comment]
I have fixed this error, thank you.
