### ISSUE TITLE
How to highlight a line based on search start/end index?

### ISSUE THREAD

**Issue by LeleDallas** [uiwjs/react-codemirror#678]
Hi 👋
Is possible to highlight a text based on file text indices? Is also possible to highlight multiple word in the same way?

For example using a file of found words defined like this:
``` ts
[ 
    {"start":100, "end":110},
    {"start":212, "end":230},
    {"start":252, "end":260},
]
```

**Comment by jaywcjlove** [comment]
@LeleDallas I didn't understand what needs to be done.

**Comment by LeleDallas** [comment]
Let me explain it better:

I have a piece of text, and I want to highlight specific portions of this text. The portions I want to highlight are defined by a list of start and end indices.

For example, if I have a text string: 

"This is an example sentence for highlighting."

And I want to highlight certain parts of it. The parts to highlight are defined by start and end indices, like this:

```
[
    {"start":5, "end":7},   // This will highlight "is"
    {"start":11, "end":18}, // This will highlight "example"
    {"start":27, "end":38}  // This will highlight "highlighting"
]
```

**Comment by jaywcjlove** [comment]
@LeleDallas  If you want to customize syntax highlighting, the tutorial is here. https://codemirror.net/examples/lang-package/

**Comment by LeleDallas** [comment]
I just wanna to highlight search result from a text string positons

**Comment by jaywcjlove** [comment]
@LeleDallas  You need to customize an extension, and you can refer to https://codemirror.net/examples/lang-package/.

**Comment by LeleDallas** [comment]
I don't understand how to create it. It must to be like the old markText functionality

**Comment by LeleDallas** [comment]
I finally did it!

Here the solution for newcomers:
```typescript

const getDecorations = (
  highlights: Array<{ start: number; end: number }> = []
) => {
  const decorations = highlights.map(({ start, end }) =>
    Decoration.mark({
      attributes: { style: "background-color: #dadb1699" },
    }).range(start, end)
  );
  return Decoration.set(decorations);
};

const highlightPlugin = (
  highlights: Array<{ start: number; end: number }>
) =>
  ViewPlugin.fromClass(
    class {
      decorations: DecorationSet;
      constructor() {
        this.decorations = getDecorations(highlights);
      }

      update(update: ViewUpdate) {
        if (update.docChanged || update.viewportChanged) {
          this.decorations = getDecorations();
        }
      }
    },
    {
      decorations: (v) => v.decorations,
    }
  );

return(
  <ReactCodeMirror
        extensions={[defaultEditorExtensions, highlightPlugin(highlights)]}
        editable={contentEditable}
        theme={isDark ? githubDark : githubLight}
        style={style}
        value={value}
      />
)
``` 

Result:
![image](https://github.com/user-attachments/assets/729ccfb7-616c-4a9a-b992-3f36850d7127)
