### ISSUE TITLE
如何为特定位置的单词添加样式？

### ISSUE THREAD

**Issue by hyunicode** [uiwjs/react-codemirror#679]
我的需求是，根据错误在代码中精确划线，翻了一圈有一个issue比较接近，但看了一下还是没什么头绪解决
https://github.com/uiwjs/react-codemirror/issues/452

或者说像以下提到的方案如何在react-codemirror里实现呢
https://discuss.codemirror.net/t/mark-text-with-only-character-position/1151
https://discuss.codemirror.net/t/adding-a-highlight-to-a-single-character-by-position/567
```typescript
const errorData = [
    { from: { line: 1, ch: 0 }, to: { line: 1, ch: 5 }, message: "错误1" },
    { from: { line: 3, ch: 0 }, to: { line: 3, ch: 5 }, message: "错误2" },
    { from: { line: 5, ch: 0 }, to: { line: 5, ch: 5 }, message: "错误3" },
  ];
```

**Comment by hyunicode** [comment]
有办法了，自定义一个linter
原本的解决方案是使用decoration做一个插件，后来发现原生有一个linter，基于linter可以很方便地实现需求

**Comment by LeleDallas** [comment]
Hey @hyunicode I need to apply the same logic. 
Can you share your solution?

**Comment by hyunicode** [comment]
> Hey @hyunicode I need to apply the same logic. Can you share your solution?

https://codemirror.net/examples/lint/
define your custom linter, and pass it into @uiw/react-codemirror as extension
