### ISSUE TITLE
how to append data with api

### ISSUE THREAD

**Issue by lz520520** [uiwjs/react-codemirror#682]
If the data is updated externally, it is currently done by modifying the value, but this causes the entire content to be re-rendered, I would like to append new data without affecting the original content, how can this be achieved, I checked the documentation and didn't find any way to do this.

**Comment by jaywcjlove** [comment]
@lz520520  I have a component([uiwjs/react-markdown-editor/core/src/commands/code.tsx](https://github.com/uiwjs/react-markdown-editor/blob/cead45e6c722fc6074034c5112ebf18670dd8894/core/src/commands/code.tsx#L60-L67)) that might help with your issue. You can refer to the following example for updating the method:

```jsx
    view.dispatch({
      changes: {
        from: main.from,
        to: main.to,
        insert: `\`\`\`js\n${txt}\n\`\`\``,
      },
      selection: EditorSelection.range(main.from + 3, main.from + 5),
    });
```

**Comment by lz520520** [comment]
Thank you very much, referring to the example you provided I solved the problem, the following is my demo, used to append data at the end of the editor
```
  const appendText = (text: string) => {
      const view = editorRef.current?.view as EditorView;
      view.dispatch({
          changes: { from: view.state.doc.length, insert:  text},
      });
  };
```
