### ISSUE TITLE
TypeError: next is undefined. Minimal "<CodeMirror /> React Component Fails?

### ISSUE THREAD

**Issue by ryanerwin** [uiwjs/react-codemirror#72]
I'm trying to run the most basic `uiwjs/react-codemirror` example from Readme.md and it's failing now on two separate systems. (Ubuntu 20.04 and Ubuntu 20.10)

The strange thing, one week ago it react-codemirror was working fine for me.
I haven't been able to figure out what changed, but even the most basic examples are failing for me.
I've created a new empty app, and even that fails.

I'm using React 17.0.1, npm 6.14.8

```bash
npx create-react-app foo
cd foo
npm install @uiw/react-codemirror --save
npm install codemirror --save
```

src/App.js only contains:

```
import CodeMirror from '@uiw/react-codemirror';
import 'codemirror/keymap/sublime';
import 'codemirror/theme/monokai.css';

const code = 'const a = 0;';

function App() {
  return (
    <div className="App">
        <p>
          <CodeMirror
            value={code}
            options={{
              theme: 'monokai',
              keyMap: 'sublime',
              mode: 'jsx',
            }}
          />
        </p>
    </div>
  );
}

export default App;
```

```
npm start
```

When I open it under Firefox I get:

```
TypeError: next is undefined
defineOptions/<
node_modules/@uiw/react-codemirror/node_modules/codemirror/lib/codemirror.js:7723

  7720 |   var next = getKeyMap(val);
  7721 |   var prev = old != Init && getKeyMap(old);
  7722 |   if (prev && prev.detach) { prev.detach(cm, next); }
> 7723 |   if (next.attach) { next.attach(cm, prev || null); }
       | ^  7724 | });
  7725 | option("extraKeys", null);
  7726 | option("configureMouse", null);
```

When I open the this under Chrome I get a different error message, but it still fails on the same line.

```
TypeError: Cannot read property 'attach' of undefined
keyMap
node_modules/@uiw/react-codemirror/node_modules/codemirror/lib/codemirror.js:7723
  7720 |   var next = getKeyMap(val);
  7721 |   var prev = old != Init && getKeyMap(old);
  7722 |   if (prev && prev.detach) { prev.detach(cm, next); }
> 7723 |   if (next.attach) { next.attach(cm, prev || null); }
       | ^  7724 | });
  7725 | option("extraKeys", null);
  7726 | option("configureMouse", null);

```

**Comment by jaywcjlove** [comment]
@ryanerwin https://codesandbox.io/s/react-codemirror-72-n8tzd-n8tzd?file=/src/App.js

**Comment by ryanerwin** [comment]
@jaywcjlove 谢谢你的连接。

可惜我安装了一个新的干净FEDORA虚拟机，然后装了@uiw/react-codemirror但是我还遇到同一个错误。。。

![image](https://user-images.githubusercontent.com/2156415/99219950-452b8580-2810-11eb-9a27-22a3a6e2b0f5.png)

另外，你可以解释为什么这个codesandbox.io连接没有“codemirror”依赖包，但是还能“import codemirror/...吗"？

![image](https://user-images.githubusercontent.com/2156415/99219053-6db28000-280e-11eb-9734-763677917fcd.png)

如果我自己 `npm uninstall codemirror` 我会遇到 Module not found: Can't resolve codemirror/keymap/sublime

**Comment by jaywcjlove** [comment]
@ryanerwin 我文档里面没有说要安装  `codemirror` 依赖，`codemirror` 已经在包中集成了

https://github.com/uiwjs/react-codemirror/blob/06cecc633aa45851df9c448af6ac78d4214cc539/package.json#L41-L44
