### ISSUE TITLE
Getting "name.toLowerCase is not a function" when "mode" is an object

### ISSUE THREAD

**Issue by cmlad** [uiwjs/react-codemirror#83]
Brand new to Node & React, so not sure I have this right.

I tried to set option `mode` to an object, which is what CodeMirror supports and is the readme here, but it doesn't seem to work.

I get the following error:

```
Unhandled Rejection (TypeError): name.toLowerCase is not a function
```

If I am not wrong, this seems to be because [setOptions](https://github.com/uiwjs/react-codemirror/blob/f66ca323c63282e104ce0dce08f6f96cd7cc2d1a/src/index.js#L41) assumes that `mode` is a string that is passed directly to `CodeMirror.findModeByName`.

If this is a real bug (rather than me doing something wrong), I can try to raise a PR to fix.

My code is this:

```
        <CodeMirror
          value={name}
          options={{
            theme: "monokai",
            keyMap: "sublime",
            mode: {
              name: "gfm",
              highlightFormatting: true,
            },
            lineNumbers: false
          }}
        />
```

**Comment by jaywcjlove** [comment]
@cmlad I don’t know your example project, don’t know how to help you

**Comment by cmlad** [comment]
Thanks for the response @jaywcjlove, let me close this for now. I'll be further ahead in a few days and can reopen if it's still an issue.
