### ISSUE TITLE
Codemirror 6

### ISSUE THREAD

**Issue by mraghuram** [uiwjs/react-codemirror#88]
Hi, just curious to know if there is a plan to upgrade this to CodeMirror 6.

Thanks for all the amazing stuff so far.

**Comment by jaywcjlove** [comment]
@mraghuram Wait for the official version to released.

**Comment by mraghuram** [comment]
Thanks. Looks like final beta is out.

**Comment by addingama** [comment]
Any update on this?

**Comment by jaywcjlove** [comment]
@addingama Still waiting...

**Comment by jaywcjlove** [comment]
Upgrade `@uiw/react-codemirror@4.0.0-rc.4` +++

**Comment by jaywcjlove** [comment]
[![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-codemirror@4.0.0-rc.4/file/README.md) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/@uiw/react-codemirror)](https://bundlephobia.com/result?p=@uiw/react-codemirror@4.0.0-rc.4)

> ⚠️ [3.0](https://raw.githack.com/uiwjs/react-codemirror/doc3/index.html) cannot be upgraded to 4.0+

```diff
import CodeMirror from '@uiw/react-codemirror';
- import 'codemirror/mode/javascript/javascript';
+ import { javascript } from "@codemirror/lang-javascript";

const code = 'console.log("hello world!");';

<CodeMirror
  value={code}
-  options={{
-    mode: 'js',
-  }}
+  extensions={[
+    javascript({ jsx: true })
+  ]}
/>
```

**Comment by gitluck1314** [comment]
I have not found any language packs that support yaml. Can you help me?

**Comment by gitluck1314** [comment]
@jaywcjlove

**Comment by gitluck1314** [comment]
@jaywcjlove 我看[这个链接](https://toscode.gitee.com/LyqSunrise/react-codemirror#https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Fuiwjs%2Freact-codemirror%2Fissues%2F88%23issuecomment-914185563)，没有发现可以支持yaml的语言包，这是怎么回事呢？我需要你的帮助

**Comment by jaywcjlove** [comment]
@gitluck1314 https://gitee.com/uiw/react-codemirror

https://github.com/uiwjs/react-codemirror/blob/a84030f04286912a3f414022b2f386dc545258f0/extensions/langs/src/index.ts#L124
