### ISSUE TITLE
Wrong typescript signature for OnChange

### ISSUE THREAD

**Issue by caiorcferreira** [uiwjs/react-codemirror#92]
Currently the `onChange` on `react-codemirror` is:
```typescript
onChange?: (instance: CodeMirror.Editor, change: CodeMirror.EditorChangeLinkedList[]) => void;
```

However, when logging the parameter `change` I get:
```
"{"from":{"line":1,"ch":12,"sticky":null,"xRel":1,"outside":1},"to":{"line":1,"ch":12,"sticky":null,"xRel":1,"outside":1},"text":["a"],"removed":[""],"origin":"+input"}
```

Which make sense since it its a linked list. The type for the parameter `change` should simply be `CodeMirror.EditorChangeLinkedList`.

**Comment by jaywcjlove** [comment]
@caiorcferreira Upgrade `+ @uiw/react-codemirror@3.0.10`
